import type { LessonContent } from "../../../types/content";

export const classificacaoBaseadaEmRegrasContent: LessonContent = {
  id: "classificacao-baseada-em-regras",
  title: "Classificação Baseada em Regras",
  subtitle: "Como transformar descritores geométricos em decisões claras, auditáveis e úteis antes de partir para modelos treinados.",
  description: "Aula interativa sobre classificação por regras usando área, circularidade, solidez, razão de aspecto, centroide e validação visual de objetos segmentados.",
  primaryCategoryId: "inteligencia-artificial",
  secondaryCategoryId: "computacao",
  level: "Intermediário",
  estimatedTime: "45-55 min",
  tags: ["Visão Computacional", "Classificação", "Regras", "Descritores", "DataFrame", "Regionprops"],
  learningObjectives: ["Criar regras com descritores geométricos.", "Organizar objetos segmentados em uma tabela interpretável.", "Combinar limites por área, circularidade, solidez e razão de aspecto.", "Entender prioridades, conflitos e fallback entre regras.", "Validar regras com amostras visuais e matriz de erros.", "Reconhecer quando regras deixam de ser suficientes."],
  prerequisites: ["Rotulação de componentes.", "Contornos e bounding boxes.", "Circularidade, solidez e convex hull."],
  references: [
    { title: "scikit-image — Measure region properties", source: "scikit-image docs", url: "https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_regionprops.html", note: "Mostra cálculo e visualização de propriedades de regiões rotuladas." },
    { title: "scikit-image — Explore and visualize region properties with pandas", source: "scikit-image docs", url: "https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_regionprops_table.html", note: "Demonstra regionprops_table em formato compatível com pandas." },
    { title: "OpenCV — Contour Features", source: "OpenCV docs", url: "https://docs.opencv.org/4.x/dd/d49/tutorial_py_contour_features.html", note: "Base para área, perímetro, centroide, hull e bounding boxes." },
    { title: "OpenCV — Structural Analysis and Shape Descriptors", source: "OpenCV docs", url: "https://docs.opencv.org/4.x/d3/dc0/group__imgproc__shape.html", note: "Referência de descritores de forma e funções de análise estrutural." },
    { title: "Computer Vision: Algorithms and Applications", source: "Richard Szeliski", url: "https://szeliski.org/Book/", note: "Contextualiza pipelines clássicos e análise baseada em características." },
  ],
  heroVisual: "rules-hero",
  openingText: "Antes de treinar uma rede neural, muitas tarefas de visão computacional podem ser resolvidas com regras transparentes. Se o objeto é grande demais, descarte. Se é quase circular e sólido, classifique como disco. Se é alongado, classifique como risco. A força desse método está na auditabilidade: cada decisão vem de uma condição explícita, fácil de visualizar e ajustar.",
  quickFacts: [
    { title: "Regras são auditáveis", body: "Você sabe exatamente por que um objeto recebeu uma classe." },
    { title: "Tabela é o centro", body: "Cada linha representa um objeto; cada coluna, um descritor." },
    { title: "Ordem importa", body: "Regras conflitantes precisam de prioridade clara." },
    { title: "Visualize erros", body: "Ajustar limites sem olhar exemplos costuma criar fragilidade." },
  ],
  sections: [
    s("motivacao", "Motivação", "Por que começar com regras", "Regras são simples, rápidas e explicáveis quando as classes têm geometria bem definida.", "rules-motivation", undefined, ["Em muitos projetos, as classes não são abstratas: objeto pequeno, objeto redondo, objeto alongado, partícula quebrada, blob grudado. Nesses casos, descritores geométricos podem separar boa parte dos exemplos.", "A classificação baseada em regras cria uma ponte entre segmentação e aprendizado de máquina. Ela mostra quais características são úteis e onde a segmentação ainda falha.", "Mesmo quando o projeto evolui para um modelo treinado, as regras servem como baseline e como ferramenta de inspeção."], [{ type: "insight", title: "Baseline interpretável", body: "Uma regra simples bem validada é melhor do que um modelo complexo que ninguém consegue explicar." }]),
    s("tabela", "Tabela", "Uma linha por objeto", "Depois da segmentação, cada componente precisa virar uma linha de dados.", "rules-table", undefined, ["O pipeline clássico rotula componentes, calcula propriedades e monta uma tabela. Em scikit-image, regionprops_table já retorna propriedades em formato compatível com pandas. Em OpenCV, você pode montar linhas manualmente a partir dos contornos.", "Colunas comuns incluem label, area, perimeter, bbox, centroid, circularity, solidity, aspect_ratio e mean_intensity.", "Essa tabela permite filtrar, ordenar, criar regras, detectar outliers e cruzar medidas com imagens anotadas."], [{ type: "definition", title: "Tabela de objetos", body: "Estrutura em que cada linha representa um objeto segmentado e cada coluna descreve uma propriedade." }, { type: "example", title: "Colunas úteis", body: "label, area, circularity, solidity, aspect_ratio, centroid_x, centroid_y, class" }]),
    s("limites", "Limites", "Thresholds sobre descritores", "Uma regra transforma um intervalo numérico em uma decisão.", "threshold-rules", "threshold-rule-builder", ["Uma regra pode ser tão simples quanto area >= 200. Mas regras úteis geralmente combinam descritores: area mínima remove ruído, circularidade identifica redondeza, solidez evita formas quebradas.", "O limite deve nascer de dados reais. Ordene a tabela, visualize exemplos perto do corte e procure uma faixa onde os erros aumentam.", "Evite limites mágicos sem explicação: eles funcionam no notebook de hoje e quebram quando a iluminação, escala ou câmera muda."], [{ type: "formula", title: "Regra simples", body: "Classe disco quando todas as condições são verdadeiras.", formula: "area > A_min AND circularity > C_min AND solidity > S_min" }]),
    s("combinacao", "Combinação", "AND, OR e prioridade", "Regras compostas precisam declarar como condições se relacionam.", "logic-visual", "logic-composer", ["AND torna a regra mais restritiva: todas as condições devem passar. OR torna a regra mais permissiva: basta uma condição. Em visão computacional, AND costuma ser usado para garantir qualidade, e OR para capturar variações aceitáveis.", "Quando duas regras classificam o mesmo objeto, a ordem importa. Uma regra de descarte por área mínima geralmente deve rodar antes das classes finais.", "Uma boa prática é ter uma classe fallback, como indefinido, para casos fora dos padrões esperados."], [{ type: "mistake", title: "Ignorar conflito", body: "Se um objeto atende duas regras e não há prioridade, o resultado depende de detalhe de implementação." }]),
    s("calibracao", "Calibração", "Escolhendo bons cortes", "Limites devem ser calibrados com exemplos, não apenas com intuição.", "calibration-visual", "calibration-slider", ["Faça histogramas dos descritores por classe esperada, se houver rótulos. Sem rótulos, inspeccione extremos e amostras próximas aos cortes.", "Cortes muito apertados geram muitos falsos negativos. Cortes muito frouxos aumentam falsos positivos. O melhor ponto depende do custo do erro.", "Documente o motivo de cada limite: tamanho mínimo do objeto, ruído observado, geometria esperada ou requisito do domínio."], [{ type: "insight", title: "O custo do erro guia o limite", body: "Em triagem, talvez você prefira capturar suspeitos demais; em automação, talvez prefira rejeitar casos duvidosos." }]),
    s("validacao", "Validação", "Olhe os acertos e os erros", "Regras só são confiáveis quando testadas visualmente em exemplos variados.", "validation-visual", "error-gallery", ["Não basta imprimir contagens. Mostre uma grade com verdadeiros positivos, falsos positivos, falsos negativos e casos indefinidos. A imagem revela padrões que a tabela esconde.", "Se os erros se concentram em objetos grudados, o problema pode estar na segmentação. Se erros aparecem perto do limite, talvez a regra precise de uma zona cinzenta.", "Validação visual conecta número e evidência: cada regra deve sobreviver ao olhar nos casos difíceis."], [{ type: "definition", title: "Falso positivo", body: "Objeto aceito por uma regra quando deveria ser rejeitado ou pertencer a outra classe." }, { type: "definition", title: "Falso negativo", body: "Objeto rejeitado por uma regra apesar de pertencer à classe desejada." }]),
    s("zonas-cinzentas", "Incerteza", "Classe indefinida é saudável", "Nem todo objeto precisa ser forçado a uma classe final.", "uncertainty-visual", undefined, ["Objetos próximos aos limites, muito pequenos, cortados pela borda ou grudados podem receber classe indefinida. Isso evita que o sistema pareça mais certo do que realmente é.", "A classe indefinida também ajuda a coletar exemplos para melhorias futuras. Ela mostra onde novas regras, melhor segmentação ou aprendizado supervisionado podem entrar.", "Em sistemas reais, rejeitar casos duvidosos pode ser uma decisão mais segura do que classificar tudo."], [{ type: "insight", title: "Indefinido não é falha", body: "É uma saída honesta para dados fora da região confiável das regras." }]),
    s("codigo", "Código", "Implementando no notebook", "Crie uma função pequena que receba uma linha da tabela e devolva a classe.", "code-rules", undefined, ["Mantenha a função de classificação explícita. Primeiro descarte ruído e objetos inválidos; depois aplique regras específicas; por fim, retorne indefinido.", "Salve a classe em uma nova coluna do DataFrame. Em seguida, use groupby para contar classes e selecione amostras por classe para visualização.", "Se os limites ficarem numerosos, coloque-os em variáveis nomeadas no topo da célula para facilitar ajuste e documentação."], [{ type: "example", title: "Estrutura", body: "def classify(row): if row.area < min_area: return 'ruido'; ... return 'indefinido'" }]),
    s("limites-do-metodo", "Limites", "Quando regras não bastam", "Regras falham quando a variação visual é grande ou difícil de descrever com poucos descritores.", "method-limits", undefined, ["Se iluminação, textura, pose e oclusão mudam muito, regras geométricas podem virar uma coleção frágil de exceções. Esse é um sinal de que features adicionais ou modelos treinados podem ser necessários.", "Outro sinal é manutenção constante: cada nova imagem exige um novo ajuste. Nesse ponto, a regra deixa de ser simples e passa a esconder complexidade.", "Mesmo assim, o baseline por regras continua útil para comparar modelos, detectar regressões e explicar casos fáceis."], [{ type: "mistake", title: "Transformar regra em labirinto", body: "Se a árvore de ifs fica impossível de explicar, talvez o problema precise de outra abordagem." }]),
    s("quiz", "Revisão", "Quiz de revisão", "Teste limites, conflitos, validação e fallback.", undefined, "quiz", ["Revise antes de avançar para segmentação semântica."], []),
    s("glossario", "Glossário", "Vocabulário essencial", "Consolide termos usados em classificação por regras.", undefined, "glossary", ["Esses conceitos ajudam a comparar regras clássicas com modelos de deep learning."], []),
  ],
  summaryCards: [
    { title: "Regras começam na tabela", body: "Objetos segmentados viram linhas com descritores." },
    { title: "Limites precisam de dados", body: "Escolha cortes olhando exemplos reais." },
    { title: "Prioridade evita conflito", body: "A ordem das regras deve ser explícita." },
    { title: "Fallback é útil", body: "Indefinido protege contra confiança falsa." },
    { title: "Valide visualmente", body: "Erros fazem sentido quando vistos na imagem." },
    { title: "Baseline não é fim", body: "Regras indicam quando modelos treinados fazem sentido." },
  ],
  quiz: [
    q("q1", "Qual é a estrutura central para regras por objeto?", "Uma tabela com uma linha por objeto.", "A imagem RGB original apenas.", "Um histograma global único.", "a", "As regras operam sobre descritores por objeto."),
    q("q2", "O que AND faz em uma regra composta?", "Exige que todas as condições sejam verdadeiras.", "Aceita qualquer condição verdadeira.", "Remove a necessidade de limites.", "a", "AND torna a regra mais restritiva."),
    q("q3", "Por que a ordem das regras importa?", "Porque regras podem conflitar ou sobrepor classes.", "Porque pandas só aceita uma ordem alfabética.", "Porque circularidade depende do label.", "a", "Prioridade define qual regra vence."),
    q("q4", "O que é falso positivo?", "Objeto aceito indevidamente pela regra.", "Objeto correto rejeitado pela regra.", "Objeto sem área calculada.", "a", "Falso positivo é uma aceitação errada."),
    q("q5", "Qual prática ajuda a escolher limites?", "Inspecionar exemplos perto do corte.", "Escolher números aleatórios.", "Usar sempre os mesmos limites em todo projeto.", "a", "Casos próximos ao corte revelam ambiguidade."),
    q("q6", "Por que usar classe indefinida?", "Para não forçar decisão em casos duvidosos.", "Para substituir segmentação.", "Para aumentar circularidade.", "a", "Indefinido representa incerteza controlada."),
    q("q7", "Quando regras começam a ser insuficientes?", "Quando exigem muitas exceções frágeis.", "Quando há uma tabela pequena.", "Quando os objetos têm labels.", "a", "Muitas exceções indicam variação difícil de codificar."),
    q("q8", "Qual vantagem das regras sobre modelos opacos?", "Auditabilidade da decisão.", "Sempre maior acurácia.", "Dispensar validação.", "a", "Cada decisão pode ser explicada por condições."),
  ],
  glossary: [
    g("Regra", "Condição explícita que transforma descritores em decisão."),
    g("Descritor", "Medida numérica que resume uma propriedade do objeto."),
    g("Threshold", "Limite usado para separar casos aceitos e rejeitados."),
    g("Classe", "Categoria atribuída a um objeto."),
    g("Fallback", "Resultado usado quando nenhuma regra específica se aplica."),
    g("Falso positivo", "Caso aceito por engano."),
    g("Falso negativo", "Caso rejeitado por engano."),
    g("Prioridade", "Ordem que define qual regra vence em caso de conflito."),
    g("Baseline", "Solução simples usada como referência de comparação."),
    g("Regionprops", "Funções que extraem propriedades de regiões rotuladas."),
    g("Zona cinzenta", "Faixa de valores onde a decisão é incerta."),
    g("Auditabilidade", "Capacidade de explicar como uma decisão foi tomada."),
  ],
};

function s(id: string, eyebrow: string, title: string, lead: string, visual: string | undefined, interactive: string | undefined, paragraphs: string[], blocks: LessonContent["sections"][number]["blocks"]) { return { id, eyebrow, title, lead, visual, interactive, paragraphs, blocks }; }
function q(id: string, prompt: string, a: string, b: string, c: string, correctOptionId: string, feedback: string) { return { id, prompt, options: [{ id: "a", label: a }, { id: "b", label: b }, { id: "c", label: c }], correctOptionId, feedback }; }
function g(term: string, definition: string) { return { term, definition }; }
