import type { LessonContent } from "../../../types/content";

export const iaESociedadeContent: LessonContent = {
  "id": "ia-e-sociedade",
  "title": "IA e Sociedade: Trabalho, Autoria e Responsabilidade",
  "subtitle": "Como automação, criação e tomada de decisão redistribuem poder, custo e responsabilização na vida social.",
  "description": "Uma aula sobre impactos sociais da IA em trabalho, autoria, direitos, concentração de poder e responsabilidade institucional, com foco em nuance e governança.",
  "primaryCategoryId": "inteligencia-artificial",
  "secondaryCategoryId": "filosofia",
  "level": "Intermediário",
  "estimatedTime": "45-60 min",
  "tags": [
    "Sociedade",
    "Trabalho",
    "Autoria",
    "Responsabilidade",
    "Governança",
    "IA generativa"
  ],
  "learningObjectives": [
    "Distinguir automação total, automação parcial e aumento de capacidade no debate sobre trabalho.",
    "Entender por que autoria, copyright e contribuição humana se tornaram questões centrais com IA generativa.",
    "Reconhecer que responsabilidade por danos em sistemas de IA é distribuída e institucionalmente moldada.",
    "Relacionar adoção de IA a concentração de infraestrutura, assimetria de poder e desenho regulatório.",
    "Avaliar impactos sociais sem cair nem em tecnofobia simplista nem em promessas vagas de inevitabilidade.",
    "Mapear quais escolhas de governança realmente mudam o efeito social da automação."
  ],
  "prerequisites": [
    "Interesse por tecnologia e seus efeitos sociais.",
    "Noção básica de que sistemas de IA podem apoiar ou substituir partes de workflows humanos.",
    "Disposição para pensar impacto social como questão de desenho institucional, não apenas de capacidade técnica."
  ],
  "references": [
    {
      "title": "Generative AI and Jobs: A Refined Global Index of Occupational Exposure",
      "source": "ILO Working Paper 140",
      "url": "https://webapps.ilo.org/static/english/intserv/working-papers/wp140/index.html",
      "note": "Estudo detalhado sobre exposição ocupacional à IA generativa e a distinção entre automação e complementação."
    },
    {
      "title": "The OECD AI exposure measure",
      "source": "OECD",
      "url": "https://www.oecd.org/en/publications/the-oecd-ai-exposure-measure_f3da0f0a-en.html",
      "note": "Mede exposição ocupacional à IA em múltiplas capacidades e ressalta a importância do contexto institucional."
    },
    {
      "title": "Copyright Registration Guidance: Works Containing Material Generated by Artificial Intelligence",
      "source": "U.S. Copyright Office",
      "url": "https://www.copyright.gov/ai/ai%5Fpolicy%5Fguidance.pdf",
      "note": "Documento chave sobre autoria humana e registro de obras com material gerado por IA."
    },
    {
      "title": "Copyright and Artificial Intelligence, Part 2: Copyrightability Report",
      "source": "U.S. Copyright Office",
      "url": "https://www.copyright.gov/ai/Copyright-and-Artificial-Intelligence-Part-2-Copyrightability-Report.pdf?t=",
      "note": "Discussão ampla sobre autoria humana, criatividade e obras assistidas por IA."
    },
    {
      "title": "Recommendation on the Ethics of Artificial Intelligence",
      "source": "UNESCO",
      "url": "https://unesdoc.unesco.org/ark:/48223/pf0000381137.locale=en",
      "note": "Referência normativa global sobre governança, direitos e responsabilidade em IA."
    },
    {
      "title": "Ethics of Artificial Intelligence and Robotics",
      "source": "Stanford Encyclopedia of Philosophy",
      "url": "https://plato.stanford.edu/ENTRiES/ethics-ai/",
      "note": "Panorama filosófico sobre responsabilidade distribuída, poder e governança."
    }
  ],
  "heroVisual": "ia-e-sociedade-hero",
  "openingText": "Perguntar o que a IA faz “à sociedade” é abstrato demais. A questão real é mais concreta: quem ganha tempo, quem perde renda, quem passa a responder por erros automatizados, quem controla infraestrutura e quem pode contestar decisões? Sistemas de IA reorganizam trabalho, autoria e responsabilidade não por fatalidade tecnológica, mas por escolhas de adoção, regulação e desenho institucional.",
  "quickFacts": [
    {
      "title": "Nem todo impacto é substituição",
      "body": "Muitas tarefas são reconfiguradas, aceleradas ou redivididas antes de serem totalmente automatizadas."
    },
    {
      "title": "Autoria continua ligada ao humano",
      "body": "Instituições jurídicas seguem tratando autoria como categoria ancorada em contribuição humana significativa."
    },
    {
      "title": "Responsabilidade não evapora",
      "body": "Automação não elimina o dever de justificar, monitorar e reparar danos produzidos por sistemas implantados."
    }
  ],
  "sections": [
    {
      "id": "sociedade-nao-e-pano-de-fundo",
      "eyebrow": "Enquadramento",
      "title": "IA é sempre implantada dentro de instituições e mercados",
      "lead": "Não existe impacto social abstrato de IA. O mesmo sistema pode ampliar autonomia em um contexto e aprofundar precarização em outro, dependendo de contrato de trabalho, governança, poder de barganha, direito de recurso e forma de integração ao workflow.",
      "paragraphs": [
        "Por isso, falar em “inevitável substituição” ou “inevitável libertação” costuma simplificar demais. Tecnologias entram em arranjos sociais já desiguais e tendem a reforçar ou tensionar essas estruturas conforme o modo de adoção.",
        "A pergunta útil é: que tipo de coordenação entre tecnologia, organização e política está sendo criada aqui? Só então faz sentido discutir efeitos sobre trabalho, autoria ou responsabilidade."
      ],
      "visual": "ia-e-sociedade-hero",
      "blocks": [
        {
          "type": "definition",
          "title": "Impacto sociotécnico",
          "body": "Efeito produzido pela interação entre capacidade técnica, organização institucional, incentivos econômicos e normas sociais."
        },
        {
          "type": "insight",
          "title": "A mesma IA pode ter vidas sociais diferentes",
          "body": "Ferramentas semelhantes geram impactos distintos conforme regras laborais, desenho de produto e posição de poder dos usuários."
        }
      ]
    },
    {
      "id": "trabalho",
      "eyebrow": "Mundo do trabalho",
      "title": "Automação não é um botão binário entre emprego intacto e emprego extinto",
      "lead": "A literatura recente insiste em uma distinção central: tarefas, ocupações e empregos não são a mesma unidade. Um sistema pode automatizar tarefas específicas, reorganizar fluxos inteiros ou complementar profissionais sem eliminar a ocupação inteira.",
      "paragraphs": [
        "Isso importa porque o debate público frequentemente erra a escala. Dizer que “a IA substitui o jornalista” ou “a IA substitui o professor” obscurece o fato de que diferentes partes do trabalho têm graus diferentes de formalização, julgamento contextual e interação humana.",
        "A questão social, então, não é apenas quantos empregos desaparecem, mas quem absorve os ganhos de produtividade, quem arca com a intensificação do trabalho e quem perde espaço de qualificação ou autonomia."
      ],
      "visual": "ia-e-sociedade-trabalho-autoria",
      "blocks": [
        {
          "type": "definition",
          "title": "Automação de tarefa",
          "body": "Substituição ou redução do trabalho humano em partes específicas de um processo, e não necessariamente na ocupação inteira."
        },
        {
          "type": "mistake",
          "title": "Erro comum",
          "body": "Falar sobre ocupações como blocos indivisíveis, ignorando a heterogeneidade interna das tarefas que as compõem."
        }
      ]
    },
    {
      "id": "autoria",
      "eyebrow": "Criação e direito",
      "title": "Autoria com IA generativa não se reduz a “quem digitou o prompt”",
      "lead": "Ferramentas generativas embaralham criação, assistência, curadoria e pós-edição. Um prompt pode iniciar um processo criativo importante, mas instituições jurídicas continuam perguntando onde está a contribuição humana substantiva que justifica autoria e proteção.",
      "paragraphs": [
        "Isso explica por que muitos debates sobre copyright distinguem conteúdo puramente gerado por máquina de obras em que humanos selecionam, organizam, editam e transformam material gerado. A questão não é só técnica, mas normativa: o que queremos reconhecer como autoria humana relevante?",
        "Também aqui existe assimetria de poder. Grandes plataformas podem capturar valor de obras geradas ou assistidas por IA enquanto criadores individuais enfrentam opacidade sobre treinamento, licenciamento e rastreio de uso."
      ],
      "interactive": "ia-e-sociedade-conflitos",
      "blocks": [
        {
          "type": "definition",
          "title": "Autoria humana significativa",
          "body": "Contribuição criativa reconhecível de uma pessoa na seleção, organização ou transformação de uma obra assistida por IA."
        },
        {
          "type": "example",
          "title": "Exemplo",
          "body": "Usar IA para gerar variações e depois editar, combinar e curar o resultado final não é o mesmo que publicar uma saída bruta sem intervenção relevante."
        }
      ]
    },
    {
      "id": "responsabilidade",
      "eyebrow": "Dano e decisão",
      "title": "Quanto mais a IA entra em decisões sociais, mais difícil — e mais necessário — fica alocar responsabilidade",
      "lead": "Sistemas de IA podem mediar crédito, recrutamento, moderação, saúde, atendimento e administração pública. Quando erram, a cadeia causal inclui design, dados, implantação, supervisão e regras de uso. Isso torna a responsabilidade distribuída, mas não opcional.",
      "paragraphs": [
        "O risco social é a “lavagem algorítmica”: organizações apresentarem a decisão como se fosse produto neutro do sistema, obscurecendo o fato de que parâmetros, escopo e contexto de uso foram escolhas humanas e institucionais.",
        "Responsabilização séria exige mecanismos de contestação, logs, revisão humana significativa quando cabível e clareza sobre quem responde pelo quê em cada camada do sistema."
      ],
      "visual": "ia-e-sociedade-autoria-responsabilidade",
      "blocks": [
        {
          "type": "definition",
          "title": "Lavagem algorítmica",
          "body": "Uso do discurso técnico para mascarar escolhas humanas e deslocar indevidamente a responsabilidade para “o sistema”."
        },
        {
          "type": "insight",
          "title": "Responsabilidade não some porque a cadeia ficou complexa",
          "body": "Complexidade aumenta a necessidade de mapear responsabilidades, e não de desistir delas."
        }
      ]
    },
    {
      "id": "poder-infraestrutura",
      "eyebrow": "Economia política",
      "title": "Infraestrutura, dados e distribuição de poder moldam quem se beneficia da IA",
      "lead": "Modelos de grande escala dependem de compute, dados, capital e canais de distribuição concentrados. Isso cria assimetrias entre quem fornece trabalho, dados e contexto e quem captura renda, infraestrutura e posição de mercado.",
      "paragraphs": [
        "A discussão social sobre IA, portanto, não é só sobre modelos e usuários finais. É também sobre plataformas, nuvem, trabalho invisível de anotação, acesso a capacidade computacional e dependência tecnológica de organizações menores.",
        "Quando falamos em “democratização da IA”, vale perguntar: democratização para criar o quê, com quais meios, sob quais termos de uso e com qual poder real de negociação?"
      ],
      "visual": "ia-e-sociedade-cadeia-decisao",
      "blocks": [
        {
          "type": "definition",
          "title": "Concentração de infraestrutura",
          "body": "Situação em que poucos atores controlam recursos computacionais, plataformas ou modelos centrais para o ecossistema."
        },
        {
          "type": "example",
          "title": "Exemplo",
          "body": "Uma empresa pode usar IA generativa amplamente sem controlar o modelo base, ficando dependente de custo, latência e política de um fornecedor dominante."
        }
      ]
    },
    {
      "id": "transicoes",
      "eyebrow": "Adoção e política",
      "title": "O efeito da IA sobre trabalho depende de como a transição é governada",
      "lead": "Ferramentas podem ser implantadas para cortar postos, intensificar metas, requalificar equipes, redistribuir tarefas ou ampliar acesso a serviços. Não é a mesma coisa. A política de adoção define se o ganho de produtividade vira bem-estar, precarização ou concentração adicional.",
      "paragraphs": [
        "Isso torna centrais temas como negociação coletiva, transparência em monitoramento, treinamento, direito à revisão e participação dos trabalhadores no redesenho do processo. A tecnologia não escolhe esse caminho sozinha.",
        "Em outras palavras, a pergunta social relevante não é apenas “o que a IA consegue fazer?”, mas “que instituições estamos construindo ao redor do que ela consegue fazer?”."
      ],
      "interactive": "ia-e-sociedade-transicao",
      "blocks": [
        {
          "type": "definition",
          "title": "Transição justa",
          "body": "Processo de adoção tecnológica que busca repartir ganhos, reduzir danos e criar mecanismos de adaptação para grupos afetados."
        },
        {
          "type": "mistake",
          "title": "Erro comum",
          "body": "Assumir que ganhos de produtividade naturalmente se convertem em ganho social sem políticas de redistribuição ou proteção."
        }
      ]
    },
    {
      "id": "governanca",
      "eyebrow": "Governança pública",
      "title": "Boas respostas combinam técnica, direito e desenho institucional",
      "lead": "Relatórios, auditorias, regras de uso, standards jurídicos e recomendações internacionais não resolvem todos os conflitos, mas ajudam a deslocar o debate do deslumbramento técnico para a responsabilidade pública.",
      "paragraphs": [
        "O desafio é construir governança que não seja apenas decorativa. Isso inclui direito de recurso, rastreabilidade, avaliação de impacto, delimitação de escopo e atenção aos grupos que absorvem mais risco e menos ganho.",
        "Falar de IA e sociedade com nuance é admitir que não existe solução única. Há trade-offs entre inovação, coordenação, proteção, abertura e concentração — e eles precisam ser discutidos explicitamente."
      ],
      "visual": "ia-e-sociedade-governanca",
      "interactive": "ia-e-sociedade-stakeholders",
      "blocks": [
        {
          "type": "example",
          "title": "Exemplo institucional",
          "body": "Uma organização pode adotar IA para apoio a decisões, mas exigir revisão humana, monitoramento de impacto e canais de apelação para reduzir dano social."
        },
        {
          "type": "insight",
          "title": "Boa governança redistribui poder interpretativo",
          "body": "Ela cria meios para que pessoas afetadas entendam, contestem e influenciem o sistema, em vez de apenas recebê-lo pronto."
        }
      ]
    },
    {
      "id": "resumo-final",
      "eyebrow": "Síntese",
      "title": "Feche a aula vendo sociedade como desenho e disputa",
      "lead": "Revise as conexões entre trabalho, autoria, responsabilidade e infraestrutura.",
      "paragraphs": [
        "A grande lição é que a IA reconfigura tarefas e relações de poder conforme o desenho institucional da adoção; não existe impacto social inevitável fora dessas escolhas."
      ],
      "interactive": "summary-cards"
    },
    {
      "id": "quiz-revisao",
      "eyebrow": "Revisão",
      "title": "Quiz sobre IA e sociedade",
      "lead": "Teste se ficaram claros os conflitos entre automação, autoria e responsabilização.",
      "paragraphs": [
        "As perguntas retomam tarefas versus ocupações, autoria humana, lavagem algorítmica e governança da transição."
      ],
      "interactive": "quiz"
    },
    {
      "id": "glossario",
      "eyebrow": "Vocabulário",
      "title": "Glossário social e institucional da IA",
      "lead": "Consolide os termos centrais para discutir impacto social sem clichês fáceis.",
      "paragraphs": [
        "Esse vocabulário ajuda a enxergar a IA como parte de arranjos de trabalho, direito e poder."
      ],
      "interactive": "glossary"
    }
  ],
  "summaryCards": [
    {
      "title": "Trabalho é granular",
      "body": "A IA afeta tarefas, fluxos e autonomia de formas muito mais nuançadas do que “substituir ou não substituir”."
    },
    {
      "title": "Autoria continua disputada",
      "body": "Contribuição humana, curadoria e transformação seguem centrais para debates sobre copyright e reconhecimento criativo."
    },
    {
      "title": "Responsabilidade é institucional",
      "body": "Automação não dissolve deveres de justificativa, correção e reparação."
    },
    {
      "title": "Infraestrutura é poder",
      "body": "Quem controla compute, plataformas e acesso ao modelo controla parte importante da distribuição de benefícios."
    }
  ],
  "quiz": [
    {
      "id": "q1",
      "prompt": "Qual distinção ajuda mais a pensar impacto da IA no trabalho?",
      "options": [
        {
          "id": "a",
          "label": "Tarefas, ocupações e empregos não são a mesma unidade."
        },
        {
          "id": "b",
          "label": "Todo emprego é indivisível."
        },
        {
          "id": "c",
          "label": "Automação sempre elimina ocupações inteiras de uma vez."
        }
      ],
      "correctOptionId": "a",
      "feedback": "A granularidade importa: muitas vezes a IA reorganiza tarefas antes de eliminar ocupações."
    },
    {
      "id": "q2",
      "prompt": "O que significa automação de tarefa?",
      "options": [
        {
          "id": "a",
          "label": "Substituir ou reduzir partes específicas do trabalho humano em um processo."
        },
        {
          "id": "b",
          "label": "Fechar automaticamente toda uma empresa."
        },
        {
          "id": "c",
          "label": "Aumentar qualquer salário."
        }
      ],
      "correctOptionId": "a",
      "feedback": "A unidade de análise mais útil costuma ser a tarefa, não a ocupação inteira."
    },
    {
      "id": "q3",
      "prompt": "Por que autoria em IA generativa é tema complexo?",
      "options": [
        {
          "id": "a",
          "label": "Porque prompt, curadoria, edição e transformação humana podem variar muito entre casos."
        },
        {
          "id": "b",
          "label": "Porque toda saída de IA é automaticamente obra humana plena."
        },
        {
          "id": "c",
          "label": "Porque direito autoral deixou de existir."
        }
      ],
      "correctOptionId": "a",
      "feedback": "A contribuição humana precisa ser analisada em grau e tipo, não presumida ou negada automaticamente."
    },
    {
      "id": "q4",
      "prompt": "O que é lavagem algorítmica?",
      "options": [
        {
          "id": "a",
          "label": "Usar o sistema como desculpa para esconder escolhas humanas e institucionais."
        },
        {
          "id": "b",
          "label": "Limpar dados com Python."
        },
        {
          "id": "c",
          "label": "Apagar logs depois de um experimento."
        }
      ],
      "correctOptionId": "a",
      "feedback": "A expressão aponta para o deslocamento indevido da responsabilidade para “o algoritmo”."
    },
    {
      "id": "q5",
      "prompt": "Qual fator ajuda a explicar quem ganha mais com IA em larga escala?",
      "options": [
        {
          "id": "a",
          "label": "Controle de infraestrutura, dados e distribuição."
        },
        {
          "id": "b",
          "label": "A cor da interface."
        },
        {
          "id": "c",
          "label": "Uso de emojis na documentação."
        }
      ],
      "correctOptionId": "a",
      "feedback": "Infraestrutura e posição de mercado moldam fortemente a captura de valor no ecossistema."
    },
    {
      "id": "q6",
      "prompt": "O que uma transição justa procura fazer?",
      "options": [
        {
          "id": "a",
          "label": "Repartir ganhos, reduzir danos e criar adaptação para grupos afetados."
        },
        {
          "id": "b",
          "label": "Acelerar automação sem debate."
        },
        {
          "id": "c",
          "label": "Evitar qualquer inovação."
        }
      ],
      "correctOptionId": "a",
      "feedback": "A ideia é governar a adoção tecnológica de modo socialmente mais equilibrado."
    },
    {
      "id": "q7",
      "prompt": "Qual leitura é mais prudente sobre responsabilidade em sistemas de IA?",
      "options": [
        {
          "id": "a",
          "label": "Ela é distribuída, mas precisa ser explicitamente mapeada e operacionalizada."
        },
        {
          "id": "b",
          "label": "Ela some quando o modelo age automaticamente."
        },
        {
          "id": "c",
          "label": "Ela pertence exclusivamente ao usuário final."
        }
      ],
      "correctOptionId": "a",
      "feedback": "Responsabilidade distribuída não significa responsabilidade inexistente."
    },
    {
      "id": "q8",
      "prompt": "Qual é a principal lição da aula?",
      "options": [
        {
          "id": "a",
          "label": "Impactos sociais da IA dependem de instituições, regras e desenho de adoção."
        },
        {
          "id": "b",
          "label": "Toda IA necessariamente melhora a vida social."
        },
        {
          "id": "c",
          "label": "Toda IA necessariamente destrói trabalho de forma uniforme."
        }
      ],
      "correctOptionId": "a",
      "feedback": "A tecnologia opera dentro de arranjos sociais e seus efeitos variam conforme essas escolhas."
    }
  ],
  "glossary": [
    {
      "term": "Impacto sociotécnico",
      "definition": "Efeito produzido pela interação entre técnica, instituições, incentivos e normas sociais."
    },
    {
      "term": "Automação de tarefa",
      "definition": "Substituição ou redução do trabalho humano em partes específicas de um processo."
    },
    {
      "term": "Aumento de capacidade",
      "definition": "Uso da IA para ampliar produtividade ou alcance do trabalho humano sem eliminar necessariamente a tarefa."
    },
    {
      "term": "Autoria humana significativa",
      "definition": "Contribuição criativa humana relevante em obra assistida por IA."
    },
    {
      "term": "Lavagem algorítmica",
      "definition": "Uso do sistema para ocultar escolhas humanas e deslocar indevidamente a responsabilidade."
    },
    {
      "term": "Transição justa",
      "definition": "Adoção tecnológica acompanhada de medidas para repartir ganhos e reduzir danos sociais."
    },
    {
      "term": "Concentração de infraestrutura",
      "definition": "Controle de compute, plataformas ou modelos centrais por poucos atores."
    },
    {
      "term": "Recurso",
      "definition": "Mecanismo pelo qual uma pessoa afetada pode contestar ou revisar uma decisão automatizada."
    },
    {
      "term": "Governança de IA",
      "definition": "Conjunto de regras, processos e responsabilidades que moldam como sistemas de IA são desenvolvidos e usados."
    },
    {
      "term": "Precarização algorítmica",
      "definition": "Degradação de autonomia, remuneração ou condições de trabalho associada ao uso de sistemas automatizados."
    }
  ]
};
