import type { LessonContent } from "../../../types/content";

export const pipelineClassicoVsDeepLearningSegmentacaoContent: LessonContent = {
  id: "pipeline-classico-vs-deep-learning-segmentacao",
  title: "Pipeline Clássico vs Deep Learning para Segmentação",
  subtitle: "Como escolher entre thresholding, morfologia e regras ou redes neurais de predição densa.",
  description: "Aula interativa comparando pipelines clássicos e deep learning para segmentação, critérios de escolha, dados, interpretabilidade, robustez, custo e abordagens híbridas.",
  primaryCategoryId: "inteligencia-artificial",
  secondaryCategoryId: "computacao",
  level: "Intermediário",
  estimatedTime: "45-55 min",
  tags: ["Visão Computacional", "Segmentação", "Pipeline Clássico", "Deep Learning", "Thresholding", "Arquitetura"],
  learningObjectives: ["Comparar pipelines clássicos e deep learning em segmentação.", "Identificar quando thresholding e morfologia são suficientes.", "Reconhecer quando redes neurais são mais adequadas.", "Avaliar custo de dados, anotação, computação e manutenção.", "Projetar pipelines híbridos com pré e pós-processamento.", "Documentar decisões técnicas com base em evidências visuais e métricas."],
  prerequisites: ["Thresholding e histogramas.", "Morfologia e componentes conectados.", "Segmentação semântica e por instâncias."],
  references: [
    { title: "OpenCV — Image Thresholding", source: "OpenCV docs", url: "https://docs.opencv.org/4.x/d7/d4d/tutorial_py_thresholding.html", note: "Documenta thresholding simples, adaptativo e Otsu." },
    { title: "scikit-image — Thresholding", source: "scikit-image docs", url: "https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_thresholding.html", note: "Mostra Otsu, histogramas e comparação de algoritmos de thresholding." },
    { title: "Fully Convolutional Networks for Semantic Segmentation", source: "Long, Shelhamer e Darrell — arXiv/CVPR", url: "https://arxiv.org/abs/1411.4038", note: "Marco de redes totalmente convolucionais para segmentação pixel-a-pixel." },
    { title: "U-Net: Convolutional Networks for Biomedical Image Segmentation", source: "Ronneberger, Fischer e Brox — arXiv/MICCAI", url: "https://arxiv.org/abs/1505.04597", note: "Arquitetura encoder-decoder amplamente usada em segmentação com poucos dados anotados." },
    { title: "TorchVision — Models and pre-trained weights", source: "PyTorch docs", url: "https://pytorch.org/vision/stable/models.html", note: "Documenta modelos para classificação, segmentação semântica, detecção e instâncias." },
  ],
  heroVisual: "pipeline-hero",
  openingText: "Nem todo problema de segmentação precisa de deep learning. Às vezes, thresholding, morfologia e descritores resolvem com menos dados, menos custo e mais explicação. Em outros casos, iluminação, textura, variação visual e ambiguidade tornam regras frágeis, e uma rede treinada passa a ser o caminho certo. A engenharia está em escolher o menor pipeline confiável para o problema real.",
  quickFacts: [
    { title: "Clássico é transparente", body: "Cada etapa pode ser visualizada e ajustada diretamente." },
    { title: "Deep aprende variação", body: "Redes capturam padrões difíceis de codificar manualmente." },
    { title: "Dados mudam tudo", body: "Sem máscaras anotadas, deep learning supervisionado perde força." },
    { title: "Híbridos são comuns", body: "Pré e pós-processamento clássico ainda ajudam modelos neurais." },
  ],
  sections: [
    s("mapa", "Visão Geral", "Duas filosofias de segmentação", "Pipelines clássicos codificam regras; deep learning aprende padrões a partir de dados.", "pipeline-map", "pipeline-selector", ["O pipeline clássico transforma imagem em máscara por etapas explícitas: cinza, blur, threshold, morfologia, componentes e filtros. Cada transformação é controlável.", "Deep learning aprende uma função a partir de exemplos anotados. O modelo recebe imagem e produz máscara sem que você defina manualmente cada regra visual.", "A pergunta prática não é qual é mais moderno, mas qual é mais confiável, barato e sustentável para o cenário."], [{ type: "insight", title: "Menor pipeline confiável", body: "Use a solução mais simples que atende às métricas e resiste à variação esperada." }]),
    s("classico", "Clássico", "Quando thresholding funciona bem", "Métodos clássicos brilham quando o contraste e a geometria são previsíveis.", "classic-pipeline", "classic-knobs", ["Se objeto e fundo têm intensidades separáveis, Otsu, threshold global ou adaptativo podem gerar máscaras excelentes. Morfologia remove ruído e fecha falhas; componentes conectados isolam objetos.", "Esse caminho é rápido, explicável e não exige dataset anotado extenso. Também é fácil de depurar: cada etapa produz uma imagem intermediária.", "A fragilidade aparece quando iluminação, textura, sombra e aparência variam além do que regras simples conseguem cobrir."], [{ type: "example", title: "Fluxo clássico", body: "grayscale → blur → threshold → opening/closing → labels → descritores" }]),
    s("deep", "Deep Learning", "Quando aprender é melhor", "Redes são úteis quando a fronteira visual é complexa demais para regras manuais.", "deep-pipeline", "data-cost-slider", ["Se a classe depende de textura, contexto, forma variável ou padrões sutis, uma rede pode aprender pistas que thresholding não vê.", "Modelos de segmentação semântica e por instâncias lidam melhor com variação, mas exigem dados anotados, treino, validação, versionamento e monitoramento.", "O custo muda de ajuste manual para curadoria de dados e manutenção do modelo."], [{ type: "definition", title: "Predição densa", body: "Saída de modelo que produz decisão espacial para pixels ou regiões da imagem." }]),
    s("criterios", "Critérios", "Como decidir", "Escolha olhando contraste, variabilidade, dados, custo e risco.", "decision-criteria", undefined, ["Comece testando uma baseline clássica simples. Se ela falha em casos variados, documente os padrões de erro. Isso revela se o problema é iluminação, textura, oclusão ou classe ambígua.", "Deep learning faz mais sentido quando há exemplos representativos e um ganho claro sobre regras. Sem dados suficientes, uma rede pode apenas memorizar o conjunto pequeno.", "Também pese interpretabilidade, latência, ambiente de execução e facilidade de manutenção pela equipe."], [{ type: "insight", title: "Baseline antes do modelo", body: "Uma baseline clássica dá referência de qualidade e ajuda a justificar complexidade extra." }]),
    s("dados", "Dados", "O preço da anotação", "Máscaras anotadas são o combustível e o gargalo do deep learning supervisionado.", "data-visual", undefined, ["No clássico, você investe tempo desenhando regras. No deep learning, investe tempo anotando, revisando e expandindo dados. Nenhum dos dois é grátis.", "Anotações inconsistentes criam teto de qualidade. Se o domínio muda, novos exemplos precisam entrar no ciclo de treino e validação.", "Para problemas com poucas imagens e contraste estável, o clássico pode ser muito mais eficiente."], [{ type: "mistake", title: "Treinar sem diversidade", body: "Um modelo com poucas variações reais tende a falhar fora do conjunto de teste confortável." }]),
    s("interpretabilidade", "Interpretabilidade", "Depuração e confiança", "Pipelines clássicos explicam etapas; modelos neurais exigem inspeção diferente.", "debug-visual", undefined, ["No clássico, você consegue apontar: o threshold falhou, o opening removeu demais, a conectividade juntou objetos. Em deep learning, o erro pode vir de dados, arquitetura, treino, domínio ou pós-processamento.", "Isso não torna redes inúteis, mas muda a prática: salve predições, confiança, exemplos difíceis e versões de modelo.", "Para aplicações críticas, explique limitações e crie fallback humano ou regra de rejeição."], [{ type: "definition", title: "Depurabilidade", body: "Facilidade de entender onde e por que um pipeline falhou." }]),
    s("robustez", "Robustez", "Variação do mundo real", "O pipeline deve ser testado contra mudanças esperadas, não apenas imagens ideais.", "robustness-visual", "stress-test", ["Mude iluminação, escala, ruído, foco, fundo e oclusão. Pipelines clássicos podem quebrar de forma previsível; modelos neurais podem degradar silenciosamente.", "Robustez não é propriedade abstrata: ela precisa ser medida com amostras representativas e casos de borda.", "A melhor solução é a que falha de modo conhecido e monitorável."], [{ type: "insight", title: "Teste de estresse", body: "Se você sabe como o sistema quebra, consegue projetar alertas e fallback." }]),
    s("hibridos", "Híbridos", "O melhor dos dois mundos", "Deep learning e visão clássica frequentemente trabalham juntos.", "hybrid-visual", undefined, ["Você pode usar pré-processamento clássico para normalizar iluminação, uma rede para segmentar e pós-processamento morfológico para remover regiões pequenas.", "Também pode usar deep learning para gerar máscara inicial e descritores clássicos para validar ou classificar objetos.", "Pipelines híbridos são comuns porque combinam aprendizado com regras de domínio explícitas."], [{ type: "example", title: "Híbrido", body: "normalização → U-Net → remove_small_objects → componentes → métricas" }]),
    s("entrega", "Entrega", "Como documentar a escolha", "Uma boa entrega mostra evidência, não opinião.", "report-visual", undefined, ["Mostre exemplos de sucesso e falha para ambos os caminhos. Compare métricas, tempo de execução, custo de anotação, manutenção e requisitos de hardware.", "Documente parâmetros clássicos ou versão do modelo, dataset usado, critérios de validação e casos fora de escopo.", "Essa documentação protege o projeto de decisões baseadas apenas em moda ou preferência pessoal."], [{ type: "insight", title: "Decisão técnica é evidência", body: "A escolha do pipeline deve ser justificável por dados, exemplos e restrições reais." }]),
    s("quiz", "Revisão", "Quiz de revisão", "Teste critérios de escolha, tradeoffs e pipelines híbridos.", undefined, "quiz", ["Feche a trilha conectando visão clássica e deep learning."], []),
    s("glossario", "Glossário", "Termos essenciais", "Revise o vocabulário final da trilha de segmentação.", undefined, "glossary", ["Esses termos ajudam a planejar projetos reais de segmentação."], []),
  ],
  summaryCards: [
    { title: "Clássico é ótimo com contraste", body: "Thresholding e morfologia resolvem bem cenários controlados." },
    { title: "Deep aprende variação", body: "Redes são fortes quando regras manuais ficam frágeis." },
    { title: "Dados têm custo", body: "Máscaras anotadas exigem tempo, critério e revisão." },
    { title: "Baseline primeiro", body: "Teste o simples antes de justificar o complexo." },
    { title: "Robustez precisa teste", body: "Use casos de borda, não só exemplos bonitos." },
    { title: "Híbridos são práticos", body: "Pré, modelo e pós-processamento podem cooperar." },
  ],
  quiz: [
    q("q1", "Quando um pipeline clássico tende a funcionar bem?", "Quando contraste e geometria são previsíveis.", "Quando não há diferença visual nenhuma.", "Somente com milhões de máscaras anotadas.", "a", "Regras explícitas funcionam melhor em cenários controlados."),
    q("q2", "Qual é um custo central do deep learning supervisionado?", "Anotação e curadoria de dados.", "Escolher apenas um threshold global.", "Nunca validar resultados.", "a", "Modelos dependem de exemplos representativos."),
    q("q3", "Por que criar baseline clássica?", "Para ter referência simples de qualidade e erro.", "Para impedir uso de redes.", "Para apagar métricas.", "a", "Baseline ajuda a justificar complexidade."),
    q("q4", "O que caracteriza pipeline híbrido?", "Combinar etapas clássicas e modelo neural.", "Usar apenas uma caixa manual.", "Remover toda validação visual.", "a", "Pré e pós-processamento clássicos podem apoiar deep learning."),
    q("q5", "Qual risco de treinar com poucos exemplos parecidos?", "Falhar fora do domínio confortável.", "Gerar threshold de Otsu perfeito sempre.", "Eliminar necessidade de teste.", "a", "Pouca diversidade limita generalização."),
    q("q6", "O que torna o clássico mais depurável?", "Etapas intermediárias explícitas.", "Ausência total de parâmetros.", "Uso obrigatório de GPU.", "a", "Cada transformação pode ser visualizada."),
    q("q7", "O que um teste de estresse deve variar?", "Iluminação, ruído, escala, fundo e oclusão.", "Apenas o nome dos arquivos.", "Somente a cor da interface.", "a", "Robustez precisa cobrir variações reais."),
    q("q8", "Como documentar a escolha do pipeline?", "Com métricas, exemplos, falhas, custo e restrições.", "Com opinião sem evidência.", "Com apenas uma imagem de sucesso.", "a", "Decisão técnica precisa ser rastreável."),
  ],
  glossary: [
    g("Pipeline clássico", "Sequência explícita de operações de processamento de imagem."),
    g("Deep learning", "Aprendizado de padrões por redes neurais treinadas com dados."),
    g("Baseline", "Solução inicial simples usada como referência."),
    g("Thresholding", "Separação de pixels por limite de intensidade."),
    g("Morfologia", "Operações que alteram formas em máscaras binárias."),
    g("Predição densa", "Saída espacial com decisão por pixel ou região."),
    g("Generalização", "Capacidade de funcionar em dados não vistos."),
    g("Domínio", "Conjunto de condições visuais do problema real."),
    g("Pós-processamento", "Etapas aplicadas depois da predição para refinar resultado."),
    g("Fallback", "Ação alternativa quando o sistema não é confiável."),
    g("Depurabilidade", "Facilidade de encontrar a causa de uma falha."),
    g("Pipeline híbrido", "Combinação de visão clássica e modelos aprendidos."),
  ],
};

function s(id: string, eyebrow: string, title: string, lead: string, visual: string | undefined, interactive: string | undefined, paragraphs: string[], blocks: LessonContent["sections"][number]["blocks"]) { return { id, eyebrow, title, lead, visual, interactive, paragraphs, blocks }; }
function q(id: string, prompt: string, a: string, b: string, c: string, correctOptionId: string, feedback: string) { return { id, prompt, options: [{ id: "a", label: a }, { id: "b", label: b }, { id: "c", label: c }], correctOptionId, feedback }; }
function g(term: string, definition: string) { return { term, definition }; }
