import type { LessonContent } from "../../../types/content";

export const momentosCentroMassaOrientacaoContent: LessonContent = {
  id: "momentos-centro-massa-orientacao",
  title: "Momentos, Centro de Massa e Orientação",
  subtitle: "Como resumir a distribuição espacial dos pixels para localizar centroide, assimetria e direção principal do objeto.",
  description: "Aula interativa sobre momentos de imagem, cv2.moments, centroide, centro de massa, momentos centrais, orientação e diferença entre centroide e centro da bounding box.",
  primaryCategoryId: "inteligencia-artificial",
  secondaryCategoryId: "computacao",
  level: "Intermediário",
  estimatedTime: "40-50 min",
  tags: ["Visão Computacional", "Momentos", "Centroide", "Centro de Massa", "Orientação", "OpenCV"],
  learningObjectives: [
    "Entender momentos como somatórios ponderados das posições dos pixels.",
    "Calcular centroide com M10/M00 e M01/M00.",
    "Diferenciar centroide, centro de massa e centro da bounding box.",
    "Compreender momentos centrais e sua relação com dispersão espacial.",
    "Interpretar orientação principal de objetos alongados.",
    "Evitar erros com M00 igual a zero e contornos degenerados.",
  ],
  prerequisites: ["Contornos e blobs.", "Coordenadas de imagem.", "Área e bounding box."],
  references: [
    { title: "OpenCV — Image Moments", source: "OpenCV docs", url: "https://docs.opencv.org/4.x/dd/d49/tutorial_py_contour_features.html", note: "Tutorial oficial sobre momentos, centroide, área e perímetro." },
    { title: "OpenCV — Moments API", source: "OpenCV docs", url: "https://docs.opencv.org/4.x/d3/dc0/group__imgproc__shape.html", note: "Documenta cv2.moments e descritores de forma." },
    { title: "Digital Image Processing", source: "Gonzalez & Woods", url: "https://www.imageprocessingplace.com/", note: "Fundamentos matemáticos de momentos e descritores." },
    { title: "Computer Vision: Algorithms and Applications", source: "Richard Szeliski", url: "https://szeliski.org/Book/", note: "Contexto de descritores geométricos e análise de forma." },
    { title: "Image Moments", source: "MathWorld", url: "https://mathworld.wolfram.com/ImageMoment.html", note: "Referência matemática sobre momentos de imagem." },
  ],
  heroVisual: "momentos-hero",
  openingText: "Área e bounding box dizem quanto um objeto ocupa e onde está seu retângulo. Mas elas não dizem como a massa de pixels está distribuída. Momentos de imagem respondem justamente isso: se os pixels fossem uma massa física, onde estaria seu centro? Para qual direção a forma se alonga? Quão espalhada ela é? Esses descritores conectam geometria, física intuitiva e código OpenCV.",
  quickFacts: [
    { title: "M00 é área", body: "O momento M00 representa a massa total do objeto, equivalente à área para binários." },
    { title: "Centroide vem de razão", body: "cx = M10/M00 e cy = M01/M00." },
    { title: "Centroide não é bbox", body: "O centro da caixa ignora a distribuição real dos pixels." },
    { title: "Orientação vem da dispersão", body: "Momentos centrais mostram o eixo principal de alongamento." },
  ],
  sections: [
    s("motivacao", "Motivação", "Além de área: onde está a massa do objeto?", "Momentos resumem a distribuição espacial dos pixels, não apenas o tamanho do blob.", "momentos-motivacao", undefined, ["Duas formas podem ter a mesma área e bounding box, mas distribuições muito diferentes. Uma pode concentrar pixels à esquerda, outra à direita; uma pode ser vertical, outra inclinada.", "Momentos tratam o objeto como uma massa distribuída no plano. Cada pixel contribui para somatórios que revelam centro, espalhamento e orientação.", "Essas medidas são úteis para anotar objetos, alinhar formas, comparar simetria e preparar descritores mais avançados."], [{ type: "insight", title: "Momentos são física aplicada à imagem", body: "A intuição é a mesma do centro de massa: pixels têm posição e massa; os momentos resumem essa distribuição." }]),
    s("momentos-basicos", "Definição", "O que são momentos de imagem", "Momentos são somatórios das coordenadas dos pixels ponderados por intensidade ou presença.", "momentos-basicos", undefined, ["Em imagem binária, cada pixel do objeto vale 1 e o fundo vale 0. O momento M00 soma todos os pixels do objeto. M10 soma as posições x dos pixels; M01 soma as posições y.", "Ao dividir M10 e M01 por M00, obtemos a média das coordenadas dos pixels, isto é, o centroide.", "Em imagens grayscale, momentos podem ser ponderados pela intensidade, aproximando a ideia de massa luminosa."], [{ type: "definition", title: "Momento de imagem", body: "Somatório que combina posições dos pixels e valores da imagem para descrever distribuição espacial." }, { type: "formula", title: "Centroide", body: "Razão entre momentos de primeira ordem e massa total.", formula: "cx = M10 / M00; cy = M01 / M00" }]),
    s("centroide", "Centroide", "Calculando centro de massa", "O centroide é a média espacial dos pixels do objeto.", "centroide-visual", "centroide-playground", ["cv2.moments(cnt) retorna um dicionário com momentos como m00, m10 e m01. Se m00 não for zero, o centroide é calculado por cx = m10/m00 e cy = m01/m00.", "Esse ponto pode cair fora da região visível em formas vazadas ou côncavas, mas ainda representa a média da distribuição dos pixels.", "O centroide é útil para escrever labels na imagem, calcular distâncias entre objetos e sincronizar tabelas com visualizações."], [{ type: "example", title: "Código OpenCV", body: "M = cv2.moments(cnt); cx = M['m10']/M['m00']; cy = M['m01']/M['m00']" }, { type: "mistake", title: "Não testar M00", body: "Contornos degenerados podem ter M00 = 0. Dividir por zero quebra o código." }]),
    s("bbox-vs-centroide", "Comparação", "Centroide vs centro da bounding box", "O centro da caixa é geométrico; o centroide depende dos pixels reais.", "bbox-vs-centroide", "bbox-centroid-comparison", ["O centro da bounding box é calculado por x + w/2, y + h/2. Ele só considera o retângulo envolvente, não a distribuição interna dos pixels.", "O centroide considera todos os pixels do objeto. Em uma forma em L, o centro da caixa pode ficar numa região vazia, enquanto o centroide se desloca para onde há mais pixels.", "Ambos podem ser úteis, mas respondem perguntas diferentes: onde está a caixa? onde está a massa?"], [{ type: "definition", title: "Centro da bounding box", body: "Ponto central do retângulo envolvente, calculado sem considerar a distribuição interna dos pixels." }, { type: "insight", title: "Perguntas diferentes", body: "BBox center localiza o retângulo; centroide localiza a massa da forma." }]),
    s("momentos-centrais", "Aprofundamento", "Momentos centrais: dispersão ao redor do centro", "Depois de encontrar o centroide, podemos medir como os pixels se espalham ao redor dele.", "momentos-centrais", undefined, ["Momentos centrais deslocam a origem para o centroide. Em vez de medir coordenadas absolutas, eles medem variações em torno do centro da forma.", "mu20, mu02 e mu11 capturam dispersão horizontal, vertical e correlação entre eixos. Eles são a base para estimar orientação principal.", "Essa mudança de referência torna os descritores menos dependentes da posição absoluta do objeto na imagem."], [{ type: "definition", title: "Momento central", body: "Momento calculado em relação ao centroide, descrevendo dispersão e forma independentemente da posição." }]),
    s("orientacao", "Orientação", "Eixo principal de alongamento", "Objetos alongados têm uma direção principal que pode ser estimada por momentos.", "orientacao-visual", "orientation-slider", ["Se os pixels se espalham mais em uma direção, a forma tem um eixo principal. Momentos centrais permitem estimar esse eixo sem ajustar explicitamente uma elipse.", "A orientação é útil em inspeção industrial, análise de partículas, caracteres inclinados e objetos alongados.", "Para objetos quase circulares, a orientação pode ser instável, porque não há um eixo dominante claro."], [{ type: "insight", title: "Orientação exige alongamento", body: "Se a forma é simétrica ou circular, pequenos ruídos podem mudar muito o ângulo calculado." }, { type: "mistake", title: "Confiar em orientação de objetos redondos", body: "Círculos não têm direção principal significativa; o ângulo pode ser arbitrário." }]),
    s("momentos-normalizados", "Robustez", "Normalização e invariância", "Momentos podem ser normalizados para reduzir dependência de escala.", "normalizacao-visual", undefined, ["Momentos brutos mudam quando o objeto cresce, se desloca ou é escalado. Momentos centrais e normalizados reduzem algumas dessas dependências.", "Hu Moments combinam momentos normalizados para produzir descritores mais robustos a escala, rotação e translação.", "Para a atividade, entender M00, M10, M01 e centroide já é suficiente; Hu Moments são um próximo passo natural."], [{ type: "definition", title: "Momentos de Hu", body: "Conjunto de sete descritores derivados de momentos normalizados, usados para comparar formas com maior invariância." }]),
    s("pipeline", "Pipeline", "Como usar no notebook", "Momentos entram depois dos contornos ou componentes conectados.", "pipeline-momentos", undefined, ["O fluxo prático é encontrar contornos, iterar cada cnt, calcular M = cv2.moments(cnt), checar M00 e salvar cx/cy na tabela.", "Na imagem final, desenhe o contorno, a bounding box e um ponto no centroide. Isso torna a apresentação clara e conectada ao DataFrame.", "Compare centroide e centro da bounding box para pelo menos um objeto assimétrico. Essa comparação demonstra compreensão conceitual, não só execução de código."], [{ type: "example", title: "Loop típico", body: "if M['m00'] != 0: cx = M['m10']/M['m00']; cy = M['m01']/M['m00']" }]),
    s("quiz", "Revisão", "Quiz de revisão", "Teste momentos, centroide, M00 e orientação.", undefined, "quiz", ["Revise antes de seguir para elipse equivalente, eixos e excentricidade."], []),
    s("glossario", "Glossário", "Glossário e próximos estudos", "Consolide o vocabulário dos momentos de imagem.", undefined, "glossary", ["Esses conceitos sustentam orientação, elipse equivalente e descritores de forma."], []),
  ],
  summaryCards: [
    { title: "Momentos resumem distribuição", body: "Eles transformam pixels em centro, dispersão e orientação." },
    { title: "M00 é massa", body: "Em binários, M00 equivale à área do objeto." },
    { title: "Centroide é razão", body: "cx = M10/M00 e cy = M01/M00." },
    { title: "BBox center é diferente", body: "Centro da caixa não considera onde os pixels realmente estão." },
    { title: "Orientação depende da forma", body: "Funciona melhor em objetos alongados." },
    { title: "Cheque M00", body: "Evite divisão por zero em contornos degenerados." },
  ],
  quiz: [
    q("q1", "O que M00 representa em uma imagem binária?", "A massa/área total do objeto.", "A largura da bounding box.", "O perímetro do contorno.", "a", "M00 soma os pixels do objeto; em binário, equivale à área."),
    q("q2", "Como calcular cx?", "M10 / M00.", "M00 / M10.", "M01 / M10.", "a", "O centroide em x é a média ponderada das coordenadas x."),
    q("q3", "Centroide e centro da bounding box são sempre iguais?", "Não.", "Sim.", "Só em conectividade-8.", "a", "Formas assimétricas deslocam o centroide em relação à caixa."),
    q("q4", "Por que testar M00 antes da divisão?", "Para evitar divisão por zero.", "Para converter RGB em cinza.", "Para mudar a conectividade.", "a", "Contornos degenerados podem ter área zero."),
    q("q5", "Momentos centrais medem em relação a quê?", "Ao centroide.", "Ao canto superior esquerdo.", "Ao threshold de Otsu.", "a", "Momentos centrais deslocam a origem para o centro da forma."),
    q("q6", "Orientação é mais estável em qual tipo de objeto?", "Objeto alongado.", "Objeto circular perfeito.", "Um pixel isolado.", "a", "Objetos alongados têm eixo dominante claro."),
    q("q7", "Para que serve o centroide na visualização?", "Anotar IDs e localizar objetos na imagem.", "Remover ruído automaticamente.", "Calcular threshold adaptativo.", "a", "Centroide é um ponto útil para texto e marcação."),
    q("q8", "O que Hu Moments buscam oferecer?", "Descritores mais invariantes a escala, rotação e translação.", "Uma nova imagem binária.", "Uma caixa alinhada aos eixos.", "a", "Hu Moments combinam momentos normalizados para comparação robusta de formas."),
  ],
  glossary: [
    g("Momento de imagem", "Somatório de coordenadas dos pixels ponderado por intensidade ou presença."),
    g("M00", "Momento de ordem zero; em binários, corresponde à área ou massa total."),
    g("M10", "Momento de primeira ordem em x, usado para calcular cx."),
    g("M01", "Momento de primeira ordem em y, usado para calcular cy."),
    g("Centroide", "Ponto médio da distribuição dos pixels do objeto."),
    g("Centro de massa", "Interpretação física do centroide quando pixels são tratados como massa."),
    g("Momento central", "Momento calculado em relação ao centroide."),
    g("Orientação", "Direção principal de alongamento do objeto."),
    g("Hu Moments", "Sete descritores derivados de momentos normalizados para comparação de formas."),
    g("Bounding box center", "Centro geométrico do retângulo envolvente."),
    g("cv2.moments", "Função do OpenCV que calcula momentos de um contorno ou imagem binária."),
    g("Contorno degenerado", "Contorno com área zero ou insuficiente para cálculo confiável."),
  ],
};

function s(id: string, eyebrow: string, title: string, lead: string, visual: string | undefined, interactive: string | undefined, paragraphs: string[], blocks: LessonContent["sections"][number]["blocks"]) { return { id, eyebrow, title, lead, visual, interactive, paragraphs, blocks }; }
function q(id: string, prompt: string, a: string, b: string, c: string, correctOptionId: string, feedback: string) { return { id, prompt, options: [{ id: "a", label: a }, { id: "b", label: b }, { id: "c", label: c }], correctOptionId, feedback }; }
function g(term: string, definition: string) { return { term, definition }; }
