import type { LessonContent } from "../../../types/content";

export const contornosAreaPerimetroBoundingBoxContent: LessonContent = {
  id: "contornos-area-perimetro-bounding-box",
  title: "Contornos, Área, Perímetro e Bounding Box",
  subtitle: "Como sair do blob rotulado e medir sua borda, tamanho e retângulo envolvente com OpenCV.",
  description: "Aula prática sobre cv2.findContours, contourArea, arcLength, boundingRect, área, perímetro, contorno e bounding box na descrição de objetos.",
  primaryCategoryId: "inteligencia-artificial",
  secondaryCategoryId: "computacao",
  level: "Intermediário",
  estimatedTime: "40-50 min",
  tags: ["Visão Computacional", "Contornos", "Área", "Perímetro", "Bounding Box", "OpenCV"],
  learningObjectives: [
    "Entender o que é contorno e como ele difere de componente conectado.",
    "Usar cv2.findContours para extrair bordas de blobs binários.",
    "Calcular área com cv2.contourArea e interpretar seus limites.",
    "Calcular perímetro com cv2.arcLength e entender sensibilidade a ruído.",
    "Extrair bounding box com cv2.boundingRect e usar x, y, w, h.",
    "Comparar objetos com área parecida e perímetro diferente.",
  ],
  prerequisites: ["Imagem binária limpa.", "Blobs/componentes conectados.", "Noção de coordenadas de imagem."],
  references: [
    { title: "OpenCV — Contours: Getting Started", source: "OpenCV docs", url: "https://docs.opencv.org/4.x/d4/d73/tutorial_py_contours_begin.html", note: "Tutorial oficial sobre extração e uso de contornos." },
    { title: "OpenCV — Structural Analysis and Shape Descriptors", source: "OpenCV docs", url: "https://docs.opencv.org/4.x/d3/dc0/group__imgproc__shape.html", note: "Documenta findContours, contourArea, arcLength e boundingRect." },
    { title: "Digital Image Processing", source: "Gonzalez & Woods", url: "https://www.imageprocessingplace.com/", note: "Referência clássica sobre análise de regiões e descritores geométricos." },
    { title: "Computer Vision: Algorithms and Applications", source: "Richard Szeliski", url: "https://szeliski.org/Book/", note: "Fundamentos de segmentação, bordas e análise de forma." },
    { title: "scikit-image measure.find_contours", source: "scikit-image docs", url: "https://scikit-image.org/docs/stable/api/skimage.measure.html#skimage.measure.find_contours", note: "Alternativa em Python para extração de contornos." },
  ],
  heroVisual: "contornos-hero",
  openingText: "Depois de identificar blobs, queremos descrever cada objeto. A área informa quanto espaço ele ocupa; o perímetro descreve sua borda; a bounding box resume sua posição e tamanho com um retângulo. Essas medidas parecem simples, mas carregam escolhas importantes: contorno externo ou interno? Borda serrilhada conta? Caixa alinhada aos eixos ou rotacionada? Nesta aula, vamos medir forma sem perder o senso crítico.",
  quickFacts: [
    { title: "Contorno é borda", body: "findContours encontra sequências de pontos que delimitam regiões binárias." },
    { title: "Área mede preenchimento", body: "contourArea calcula a área encerrada pelo contorno, não necessariamente igual à contagem de pixels." },
    { title: "Perímetro mede irregularidade", body: "arcLength cresce com bordas serrilhadas e ruído." },
    { title: "Bounding box localiza", body: "boundingRect retorna x, y, largura e altura do retângulo envolvente." },
  ],
  sections: [
    s("motivacao", "Motivação", "Depois de encontrar o blob, precisamos medi-lo", "Contornos e medidas geométricas transformam uma região segmentada em atributos úteis.", "contornos-motivacao", undefined, ["Rotular componentes diz quantos objetos existem e onde estão. Mas para comparar objetos, precisamos de medidas: tamanho, borda, posição, largura e altura.", "Contornos descrevem a fronteira do objeto. Área, perímetro e bounding box resumem essa fronteira em números. Esses números viram colunas no DataFrame da atividade.", "A qualidade dessas medidas depende da qualidade da segmentação. Ruído, buracos e bordas serrilhadas podem distorcer área e perímetro."], [{ type: "insight", title: "Features nascem da geometria", body: "Antes de classificar um objeto por regras, você precisa transformar forma visual em medidas numéricas." }]),
    s("contorno", "Contorno", "O que é um contorno?", "Um contorno é uma sequência de pontos que acompanha a fronteira de uma região.", "contorno-visual", "contorno-toggle", ["Em imagens binárias, o contorno separa objeto e fundo. OpenCV representa o contorno como uma lista de pontos (x, y).", "Com cv2.findContours, podemos extrair contornos externos, internos ou hierarquias completas, dependendo do modo escolhido.", "Para medir objetos simples, RETR_EXTERNAL costuma bastar porque pega apenas contornos externos e ignora buracos internos."], [{ type: "definition", title: "Contorno", body: "Sequência ordenada de pontos que delimita a borda de uma região em uma imagem binária." }, { type: "example", title: "findContours", body: "contours, hierarchy = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)" }]),
    s("modos", "OpenCV", "RETR_EXTERNAL e CHAIN_APPROX_SIMPLE", "Os parâmetros de findContours controlam quais bordas são retornadas e como os pontos são armazenados.", "modos-contorno", undefined, ["RETR_EXTERNAL retorna apenas contornos externos. É ideal quando você quer uma região por objeto e não quer que buracos internos virem contornos separados.", "CHAIN_APPROX_SIMPLE comprime segmentos retos, guardando menos pontos. Isso reduz memória sem perder a geometria essencial da borda.", "Se você precisa analisar buracos, use modos hierárquicos como RETR_TREE. Para a maioria das medições iniciais, externo e simples são suficientes."], [{ type: "definition", title: "RETR_EXTERNAL", body: "Modo de recuperação que retorna somente os contornos externos." }, { type: "mistake", title: "Medir buracos como objetos", body: "Usar modo hierárquico sem cuidado pode fazer buracos internos aparecerem como contornos adicionais." }]),
    s("area", "Medida", "Área: quanto o objeto ocupa", "Área é uma das primeiras features de forma e tamanho.", "area-visual", "area-perimeter-comparison", ["cv2.contourArea calcula a área encerrada pelo contorno. Em muitos casos, ela é próxima da contagem de pixels do componente, mas não precisa ser exatamente igual.", "Área ajuda a filtrar ruído, separar objetos pequenos de grandes e criar regras simples de classificação.", "Mas área sozinha não descreve forma. Um círculo e um retângulo podem ter áreas parecidas e aparências muito diferentes."], [{ type: "definition", title: "Área de contorno", body: "Medida da região encerrada por um contorno, retornada por cv2.contourArea." }, { type: "example", title: "Código", body: "area = cv2.contourArea(cnt)" }]),
    s("perimetro", "Medida", "Perímetro: o comprimento da borda", "Perímetro mede o quanto a fronteira do objeto percorre a imagem.", "perimetro-visual", undefined, ["cv2.arcLength calcula o comprimento do contorno. Para objetos fechados, passamos True no segundo argumento.", "Perímetro é sensível a ruído e serrilhado. Uma borda irregular aumenta o perímetro mesmo que a área mude pouco.", "Essa sensibilidade é útil para detectar irregularidade, mas perigosa se a segmentação estiver ruidosa."], [{ type: "definition", title: "Perímetro", body: "Comprimento total da borda do objeto, calculado a partir dos pontos do contorno." }, { type: "example", title: "Código", body: "perimeter = cv2.arcLength(cnt, True)" }, { type: "mistake", title: "Comparar perímetros sem limpar ruído", body: "Bordas serrilhadas inflam o perímetro e distorcem métricas como circularidade." }]),
    s("bounding-box", "Localização", "Bounding box: x, y, w, h", "Bounding box resume posição e tamanho em um retângulo envolvente.", "bbox-visual", "bbox-inspector", ["cv2.boundingRect retorna x, y, w, h: canto superior esquerdo, largura e altura. É simples, rápido e muito útil para desenhar retângulos ao redor dos objetos.", "A caixa é alinhada aos eixos da imagem. Isso significa que, para objetos inclinados, ela pode conter bastante fundo e não representar bem a orientação real.", "Mesmo com essa limitação, bounding box é uma das features mais práticas para visualização, recorte e tabelas."], [{ type: "definition", title: "Bounding box", body: "Retângulo mínimo alinhado aos eixos que envolve o contorno ou componente." }, { type: "example", title: "Código", body: "x, y, w, h = cv2.boundingRect(cnt)" }]),
    s("area-vs-perimetro", "Comparação", "Área parecida, perímetro diferente", "Objetos com áreas similares podem ter bordas muito diferentes.", "area-vs-perimetro", undefined, ["Imagine um círculo compacto e uma estrela pontuda com a mesma área. A estrela terá perímetro muito maior por causa das reentrâncias e pontas.", "Esse contraste prepara o terreno para métricas como circularidade, solidez e convex hull, que combinam área e perímetro para descrever forma.", "Por isso, nunca use uma feature isolada quando a classe depende de geometria. Área mede tamanho; perímetro ajuda a revelar complexidade da borda."], [{ type: "insight", title: "Perímetro captura irregularidade", body: "Se a área é parecida, mas o perímetro é maior, a forma provavelmente é menos compacta ou mais serrilhada." }]),
    s("codigo-pipeline", "Pipeline", "Do contorno ao DataFrame", "O objetivo prático é transformar cada contorno em uma linha de tabela.", "pipeline-contornos", undefined, ["O pipeline é: encontrar contornos, iterar cada contorno, calcular área, perímetro e bounding box, salvar em uma lista de dicionários e converter para DataFrame.", "Essa tabela pode ser exportada, filtrada, comparada com validação manual e usada em regras de classificação.", "Na apresentação, mostre a imagem com contornos e caixas, a tabela de features e uma breve discussão sobre limitações."], [{ type: "example", title: "Estrutura de loop", body: "for i, cnt in enumerate(contours):", items: ["area = cv2.contourArea(cnt)", "perimeter = cv2.arcLength(cnt, True)", "x, y, w, h = cv2.boundingRect(cnt)"] }]),
    s("quiz", "Revisão", "Quiz de revisão", "Teste os conceitos de contorno, área, perímetro e bounding box.", undefined, "quiz", ["Revise antes de avançar para momentos e centro de massa."], []),
    s("glossario", "Glossário", "Glossário e próximos estudos", "Consolide o vocabulário essencial de descritores geométricos básicos.", undefined, "glossary", ["Esses termos serão usados nas próximas aulas de momentos, circularidade, solidez e classificação."], []),
  ],
  summaryCards: [
    { title: "Contorno é fronteira", body: "Uma lista de pontos que delimita a região do objeto." },
    { title: "Área mede tamanho", body: "contourArea estima a região encerrada pela borda." },
    { title: "Perímetro mede borda", body: "arcLength cresce com irregularidade e ruído." },
    { title: "Bounding box localiza", body: "x, y, w, h resumem posição e dimensão." },
    { title: "Tabela organiza", body: "Cada contorno vira uma linha com features." },
    { title: "Limpe antes", body: "Ruído afeta perímetro e medidas derivadas." },
  ],
  quiz: [
    q("q1", "O que cv2.findContours retorna?", "Listas de pontos que delimitam regiões.", "Apenas o número total de pixels.", "O threshold ótimo.", "a", "findContours retorna contornos, isto é, sequências de pontos de borda."),
    q("q2", "Para que serve cv2.contourArea?", "Calcular a área encerrada por um contorno.", "Calcular o centroide diretamente.", "Converter RGB em cinza.", "a", "contourArea mede a área geométrica do contorno."),
    q("q3", "Por que perímetro é sensível a ruído?", "Bordas serrilhadas aumentam o comprimento do contorno.", "Porque ignora todos os pontos diagonais.", "Porque só funciona em RGB.", "a", "Irregularidades na borda elevam arcLength."),
    q("q4", "O que boundingRect retorna?", "x, y, largura e altura.", "Área e circularidade.", "Label e centroide.", "a", "boundingRect retorna o retângulo envolvente alinhado aos eixos."),
    q("q5", "Qual modo pega apenas contornos externos?", "RETR_EXTERNAL.", "CHAIN_APPROX_SIMPLE.", "MORPH_CLOSE.", "a", "RETR_EXTERNAL ignora contornos internos como buracos."),
    q("q6", "Área sozinha distingue forma?", "Não, objetos diferentes podem ter áreas parecidas.", "Sim, sempre.", "Só se houver bounding box.", "a", "Área mede tamanho, não complexidade da forma."),
    q("q7", "Para objeto inclinado, qual limitação da bounding box simples?", "Ela é alinhada aos eixos e pode incluir muito fundo.", "Ela não tem largura.", "Ela apaga o contorno.", "a", "boundingRect não gira com o objeto."),
    q("q8", "Qual é uma boa saída prática dessa etapa?", "Um DataFrame com área, perímetro e bounding box por objeto.", "Uma imagem RGB sem labels.", "Um novo threshold automático.", "a", "Features geométricas organizadas em tabela sustentam a análise."),
  ],
  glossary: [
    g("Contorno", "Sequência de pontos que representa a fronteira de uma região."),
    g("findContours", "Função do OpenCV que extrai contornos de uma imagem binária."),
    g("RETR_EXTERNAL", "Modo que retorna apenas contornos externos."),
    g("CHAIN_APPROX_SIMPLE", "Método que comprime segmentos retos do contorno."),
    g("Área", "Medida da região ocupada ou encerrada pelo contorno."),
    g("contourArea", "Função do OpenCV que calcula área de um contorno."),
    g("Perímetro", "Comprimento da borda do objeto."),
    g("arcLength", "Função do OpenCV que calcula o comprimento do contorno."),
    g("Bounding box", "Retângulo envolvente alinhado aos eixos."),
    g("boundingRect", "Função do OpenCV que retorna x, y, w e h do retângulo envolvente."),
    g("Feature geométrica", "Medida numérica que descreve forma, tamanho ou posição."),
    g("Borda serrilhada", "Fronteira irregular causada por ruído, baixa resolução ou threshold ruim."),
  ],
};

function s(id: string, eyebrow: string, title: string, lead: string, visual: string | undefined, interactive: string | undefined, paragraphs: string[], blocks: LessonContent["sections"][number]["blocks"]) { return { id, eyebrow, title, lead, visual, interactive, paragraphs, blocks }; }
function q(id: string, prompt: string, a: string, b: string, c: string, correctOptionId: string, feedback: string) { return { id, prompt, options: [{ id: "a", label: a }, { id: "b", label: b }, { id: "c", label: c }], correctOptionId, feedback }; }
function g(term: string, definition: string) { return { term, definition }; }
