import type { LessonContent } from "../../../types/content";

export const segmentacaoSemanticaContent: LessonContent = {
  id: "segmentacao-semantica",
  title: "Segmentação Semântica",
  subtitle: "Como redes neurais atribuem uma classe a cada pixel para produzir mapas densos de significado.",
  description: "Aula interativa sobre segmentação semântica, mapas de classe, logits, softmax, U-Net, FCN, DeepLab, IoU e diferenças para detecção e instâncias.",
  primaryCategoryId: "inteligencia-artificial",
  secondaryCategoryId: "computacao",
  level: "Intermediário",
  estimatedTime: "50-60 min",
  tags: ["Visão Computacional", "Segmentação Semântica", "Deep Learning", "U-Net", "FCN", "IoU"],
  learningObjectives: ["Entender segmentação semântica como classificação por pixel.", "Diferenciar segmentação semântica, detecção e segmentação por instâncias.", "Interpretar logits, softmax e mapa final de classes.", "Compreender a intuição de arquiteturas encoder-decoder e skip connections.", "Avaliar máscaras com IoU e observar erros de borda.", "Reconhecer limitações como ambiguidade, classes raras e perda de instâncias."],
  prerequisites: ["Imagens digitais e pixels.", "Noções de classificação supervisionada.", "Segmentação clássica e máscaras binárias."],
  references: [
    { title: "Fully Convolutional Networks for Semantic Segmentation", source: "Long, Shelhamer e Darrell — arXiv/CVPR", url: "https://arxiv.org/abs/1411.4038", note: "Trabalho seminal sobre redes totalmente convolucionais para predição densa." },
    { title: "U-Net: Convolutional Networks for Biomedical Image Segmentation", source: "Ronneberger, Fischer e Brox — arXiv/MICCAI", url: "https://arxiv.org/abs/1505.04597", note: "Arquitetura encoder-decoder com conexões de atalho para localização precisa." },
    { title: "DeepLab: Semantic Image Segmentation with Deep Convolutional Nets, Atrous Convolution, and Fully Connected CRFs", source: "Chen et al. — arXiv/TPAMI", url: "https://arxiv.org/abs/1606.00915", note: "Introduz uso de convolução atrous e refinamento de bordas no contexto de segmentação semântica." },
    { title: "Rethinking Atrous Convolution for Semantic Image Segmentation", source: "Chen et al. — arXiv", url: "https://arxiv.org/abs/1706.05587", note: "Discute DeepLabv3, contexto multiescala e ASPP." },
    { title: "TorchVision — Models and pre-trained weights", source: "PyTorch docs", url: "https://pytorch.org/vision/stable/models.html", note: "Documenta modelos para tarefas como segmentação semântica, detecção e instâncias." },
  ],
  heroVisual: "semantic-hero",
  openingText: "Na segmentação semântica, a pergunta muda de 'qual é a classe da imagem?' para 'qual é a classe de cada pixel?'. O resultado não é uma caixa, nem uma lista de objetos, mas um mapa colorido em que cada posição recebe um significado: céu, estrada, célula, fundo, parede, planta. Essa ideia é poderosa porque preserva estrutura espacial e permite medir áreas, bordas e regiões com precisão pixel-a-pixel.",
  quickFacts: [
    { title: "Um rótulo por pixel", body: "Cada pixel recebe uma classe sem distinguir indivíduos da mesma classe." },
    { title: "Predição densa", body: "A rede produz um mapa alinhado à imagem, não só uma classe global." },
    { title: "Softmax por posição", body: "Cada pixel tem pontuações por classe e escolhe a mais provável." },
    { title: "IoU avalia sobreposição", body: "Compara máscara prevista e máscara de referência." },
  ],
  sections: [
    s("ideia", "Ideia Central", "Classificação por pixel", "Segmentação semântica atribui uma classe a cada posição da imagem.", "semantic-idea", "pixel-labeler", ["Em classificação, uma imagem inteira vira um rótulo. Em segmentação semântica, cada pixel vira um rótulo. O resultado é uma máscara multiclasse com o mesmo sentido espacial da imagem original.", "Isso permite responder perguntas como: onde está a estrada? quais pixels pertencem ao tumor? que regiões são vegetação? A saída é mais rica que uma caixa, porque preserva forma e fronteira.", "O termo semântica indica que os rótulos são categorias de significado, não IDs de objetos individuais."], [{ type: "definition", title: "Segmentação semântica", body: "Tarefa de atribuir uma classe semântica a cada pixel da imagem." }]),
    s("comparacao", "Comparação", "Classificação, detecção e segmentação", "Cada tarefa responde uma pergunta espacial diferente.", "task-comparison", undefined, ["Classificação responde o que aparece na imagem. Detecção responde onde há objetos usando caixas. Segmentação semântica responde quais pixels pertencem a cada classe.", "Se dois carros encostados aparecem na cena, a segmentação semântica marca ambos como carro, mas não separa carro 1 de carro 2. Essa separação é assunto da segmentação por instâncias.", "Entender essa diferença evita escolher uma técnica poderosa para a pergunta errada."], [{ type: "insight", title: "Semântica não conta indivíduos", body: "Ela sabe que pixels são 'carro', mas não distingue cada carro separado." }]),
    s("saida", "Saída do Modelo", "Logits, softmax e argmax", "A rede produz uma pontuação por classe em cada pixel.", "logits-visual", "confidence-map", ["Antes da máscara final, o modelo gera mapas de pontuação, chamados logits. Para cada pixel, há uma pontuação para cada classe. O softmax transforma essas pontuações em probabilidades relativas.", "O mapa final geralmente usa argmax: a classe com maior probabilidade vence naquele pixel. Mas a confiança também importa: pixels com probabilidades próximas indicam ambiguidade.", "Visualizar confiança ajuda a detectar bordas incertas, sombras, texturas parecidas e regiões fora do domínio de treinamento."], [{ type: "definition", title: "Logit", body: "Pontuação bruta produzida pelo modelo antes da normalização por softmax." }, { type: "example", title: "Decisão por pixel", body: "se estrada = 0.72, calçada = 0.20 e céu = 0.08, o pixel vira estrada." }]),
    s("arquiteturas", "Arquiteturas", "Encoder, decoder e skips", "Modelos modernos combinam contexto global e detalhe local.", "encoder-decoder", "architecture-toggle", ["O encoder reduz a resolução e aprende contexto: o que a região parece ser. O decoder recupera resolução para produzir uma máscara alinhada aos pixels.", "U-Net popularizou conexões de atalho entre encoder e decoder. Essas conexões carregam detalhes finos que ajudam a reconstruir bordas e estruturas pequenas.", "FCN mostrou que redes de classificação poderiam ser convertidas para predição densa. DeepLab explorou contexto multiescala com convoluções atrous."], [{ type: "definition", title: "Skip connection", body: "Ligação que leva features de alta resolução do encoder para o decoder." }, { type: "insight", title: "Contexto e detalhe competem", body: "Camadas profundas entendem significado; camadas rasas preservam bordas." }]),
    s("anotacao", "Dados", "Máscaras de referência", "Treinar segmentação semântica exige exemplos com rótulos por pixel.", "annotation-visual", undefined, ["O dado de treinamento costuma ser um par: imagem e máscara. A máscara tem um valor de classe por pixel. Em problemas reais, criar essas máscaras é caro e requer consistência entre anotadores.", "Classes raras, bordas ambíguas e objetos parcialmente visíveis tornam a anotação difícil. Se a referência é inconsistente, o modelo aprende incerteza ou padrões errados.", "A qualidade do dataset é tão importante quanto a arquitetura."], [{ type: "mistake", title: "Subestimar custo de anotação", body: "Máscaras pixel-a-pixel são muito mais trabalhosas que labels de imagem ou caixas." }]),
    s("perda", "Treinamento", "Loss pixel-a-pixel", "A perda compara a distribuição prevista com a classe correta de cada pixel.", "loss-visual", undefined, ["A forma comum de treino usa entropia cruzada por pixel. Cada posição contribui para o erro conforme a classe prevista se afasta da referência.", "Se uma classe ocupa poucos pixels, ela pode ser ignorada pelo modelo. Pesos de classe, amostragem e losses específicas ajudam a lidar com desequilíbrio.", "O treino precisa considerar aumento de dados, resolução, batch size, normalização e validação em imagens não vistas."], [{ type: "definition", title: "Entropia cruzada por pixel", body: "Loss que penaliza a previsão de classe em cada posição da máscara." }]),
    s("avaliacao", "Avaliação", "IoU e erro de borda", "Avaliar segmentação exige medir sobreposição espacial, não apenas acerto global.", "iou-visual", "iou-simulator", ["IoU compara interseção e união entre a máscara prevista e a máscara de referência. É uma métrica intuitiva: quanto da região prevista realmente coincide com o alvo?", "Acurácia por pixel pode enganar quando o fundo domina a imagem. Um modelo que prevê fundo em quase tudo pode parecer bom e ainda falhar no objeto importante.", "Bordas costumam concentrar erros. Por isso, além de IoU médio, olhe exemplos visuais."], [{ type: "formula", title: "IoU", body: "Interseção sobre união entre previsão e referência.", formula: "IoU = área(pred ∩ ref) / área(pred ∪ ref)" }, { type: "mistake", title: "Confiar só em acurácia", body: "Com muito fundo, a acurácia pode ser alta mesmo com objetos mal segmentados." }]),
    s("pos-processamento", "Pós-Processamento", "Do mapa bruto à máscara útil", "A saída do modelo pode precisar de suavização, filtros ou regras de domínio.", "postprocess-visual", undefined, ["Depois do argmax, podemos remover regiões pequenas, preencher buracos, suavizar bordas ou aplicar regras de conectividade. Isso aproxima a máscara final do uso prático.", "Mas pós-processamento não deve esconder falhas sistemáticas. Se o modelo erra sempre a mesma classe, o problema pode estar nos dados ou arquitetura.", "A etapa final deve ser documentada para que a avaliação reflita exatamente o pipeline usado."], [{ type: "example", title: "Exemplos", body: "remove_small_objects, fechamento morfológico, filtro por área e suavização de borda." }]),
    s("limitacoes", "Limitações", "Onde a semântica falha", "A tarefa não separa instâncias e pode borrar objetos pequenos ou raros.", "semantic-limits", undefined, ["Segmentação semântica agrupa todos os pixels da mesma classe. Se é importante contar objetos separados, ela não basta sozinha.", "Objetos pequenos podem desaparecer quando a rede reduz a resolução internamente. Bordas finas podem ficar borradas, especialmente em cenas com texturas parecidas.", "Mudança de domínio também pesa: um modelo treinado em uma cidade, microscópio ou câmera pode falhar em outro contexto."], [{ type: "insight", title: "Próximo passo", body: "Quando precisa separar indivíduos, entramos em segmentação por instâncias." }]),
    s("quiz", "Revisão", "Quiz de revisão", "Teste conceitos de pixel, softmax, arquitetura e IoU.", undefined, "quiz", ["Revise antes de avançar para segmentação por instâncias."], []),
    s("glossario", "Glossário", "Termos essenciais", "Fixe o vocabulário de segmentação semântica.", undefined, "glossary", ["Esses termos aparecem em papers, bibliotecas e projetos reais de visão computacional."], []),
  ],
  summaryCards: [
    { title: "Semântica é por pixel", body: "Cada posição recebe uma classe, não um ID de objeto." },
    { title: "Modelo produz mapas", body: "Logits e softmax existem para cada classe em cada pixel." },
    { title: "Encoder-decoder equilibra", body: "Contexto profundo e detalhe espacial precisam trabalhar juntos." },
    { title: "Anotação é crítica", body: "Máscaras ruins limitam o aprendizado." },
    { title: "IoU mede sobreposição", body: "Avalie regiões, não só porcentagem de pixels corretos." },
    { title: "Instâncias vêm depois", body: "Semântica não separa indivíduos da mesma classe." },
  ],
  quiz: [
    q("q1", "O que a segmentação semântica atribui a cada pixel?", "Uma classe semântica.", "Uma bounding box.", "Um ID único de instância sempre.", "a", "A saída é um mapa de classes por pixel."),
    q("q2", "O que diferencia semântica de instâncias?", "Semântica não separa indivíduos da mesma classe.", "Semântica não usa pixels.", "Instâncias só classificam a imagem inteira.", "a", "Dois carros podem virar a mesma classe carro."),
    q("q3", "Para que serve softmax na saída?", "Converter logits em probabilidades relativas por classe.", "Desenhar bounding boxes.", "Remover buracos da máscara.", "a", "Softmax normaliza pontuações por pixel."),
    q("q4", "Qual é a função do decoder?", "Recuperar resolução espacial da máscara.", "Reduzir a imagem para uma classe única.", "Apagar pixels incertos.", "a", "O decoder transforma features em mapa denso."),
    q("q5", "Por que skip connections ajudam?", "Elas carregam detalhes finos para a reconstrução.", "Elas substituem a loss.", "Elas removem necessidade de dados anotados.", "a", "Atalhos conectam features rasas a etapas de reconstrução."),
    q("q6", "O que mede IoU?", "Sobreposição entre previsão e referência.", "Tempo de treino.", "Número de classes do dataset.", "a", "IoU é interseção dividida pela união."),
    q("q7", "Por que acurácia por pixel pode enganar?", "Porque o fundo pode dominar a imagem.", "Porque só funciona em RGB.", "Porque ignora a máscara prevista.", "a", "Prever fundo em tudo pode inflar a acurácia."),
    q("q8", "Qual é um custo importante da segmentação semântica supervisionada?", "Anotar máscaras por pixel.", "Calcular apenas bounding boxes.", "Remover todas as classes raras.", "a", "Máscaras densas exigem anotação cuidadosa."),
  ],
  glossary: [
    g("Segmentação semântica", "Classificação de cada pixel em uma classe de significado."),
    g("Máscara", "Imagem de rótulos que representa classes por pixel."),
    g("Logit", "Pontuação bruta do modelo antes do softmax."),
    g("Softmax", "Normalização que transforma pontuações em probabilidades relativas."),
    g("Argmax", "Operação que escolhe a classe de maior pontuação."),
    g("Encoder", "Parte da rede que extrai contexto e reduz resolução."),
    g("Decoder", "Parte da rede que recupera resolução espacial."),
    g("Skip connection", "Atalho que leva detalhes do encoder ao decoder."),
    g("IoU", "Métrica de interseção sobre união entre máscaras."),
    g("Classe rara", "Classe com poucos pixels ou poucos exemplos no conjunto de treino."),
    g("ASPP", "Módulo de contexto multiescala usado em variantes DeepLab."),
    g("Predição densa", "Saída que produz uma decisão para muitas posições espaciais."),
  ],
};

function s(id: string, eyebrow: string, title: string, lead: string, visual: string | undefined, interactive: string | undefined, paragraphs: string[], blocks: LessonContent["sections"][number]["blocks"]) { return { id, eyebrow, title, lead, visual, interactive, paragraphs, blocks }; }
function q(id: string, prompt: string, a: string, b: string, c: string, correctOptionId: string, feedback: string) { return { id, prompt, options: [{ id: "a", label: a }, { id: "b", label: b }, { id: "c", label: c }], correctOptionId, feedback }; }
function g(term: string, definition: string) { return { term, definition }; }
