import type { LessonContent } from "../../../types/content";

export const circularidadeSolidezConvexHullContent: LessonContent = {
  id: "circularidade-solidez-convex-hull",
  title: "Circularidade, Solidez e Convex Hull",
  subtitle: "Descritores de forma para medir o quanto um objeto parece redondo, compacto ou recortado.",
  description: "Aula interativa sobre circularidade, solidez, convex hull, convexidade, defeitos convexos e uso desses descritores em regras de classificação.",
  primaryCategoryId: "inteligencia-artificial",
  secondaryCategoryId: "computacao",
  level: "Intermediário",
  estimatedTime: "45-55 min",
  tags: ["Visão Computacional", "Circularidade", "Solidez", "Convex Hull", "Descritores de Forma", "OpenCV"],
  learningObjectives: [
    "Calcular circularidade a partir de área e perímetro.",
    "Interpretar solidez como razão entre área real e área do casco convexo.",
    "Entender convex hull como envoltória convexa mínima de um conjunto de pontos.",
    "Reconhecer defeitos de convexidade e concavidades relevantes.",
    "Usar descritores de forma em regras simples de classificação.",
    "Evitar leituras erradas causadas por ruído, escala, bordas serrilhadas e buracos.",
  ],
  prerequisites: ["Contornos, área e perímetro.", "Bounding box e centroide.", "Noções de objetos binários e blobs."],
  references: [
    { title: "OpenCV — Contour Features", source: "OpenCV docs", url: "https://docs.opencv.org/4.x/dd/d49/tutorial_py_contour_features.html", note: "Documenta área, perímetro, convex hull e checagem de convexidade." },
    { title: "OpenCV — Structural Analysis and Shape Descriptors", source: "OpenCV docs", url: "https://docs.opencv.org/4.x/d3/dc0/group__imgproc__shape.html", note: "Referência de funções como contourArea, arcLength, convexHull e convexityDefects." },
    { title: "Convex Hull", source: "scikit-image docs", url: "https://scikit-image.org/docs/stable/auto_examples/edges/plot_convex_hull.html", note: "Define a envoltória convexa de uma imagem binária como o menor polígono convexo que envolve os pixels brancos." },
    { title: "skimage.measure region properties", source: "scikit-image docs", url: "https://scikit-image.org/docs/stable/api/skimage.measure.html", note: "Documenta propriedades de regiões, perímetro, momentos e medidas geométricas." },
    { title: "Computer Vision: Algorithms and Applications", source: "Richard Szeliski", url: "https://szeliski.org/Book/", note: "Contextualiza descritores geométricos em análise de forma e visão computacional." },
  ],
  heroVisual: "shape-descriptors-hero",
  openingText: "Depois de detectar um objeto, queremos descrevê-lo com números que façam sentido. Circularidade responde: quão perto de um círculo essa forma está? Solidez responde: quanto da sua envoltória convexa está realmente preenchido? Convex hull responde: qual é o contorno convexo mínimo que abraça todos os pontos? Juntos, esses descritores transformam intuição visual em critérios mensuráveis para análise e classificação.",
  quickFacts: [
    { title: "Circularidade", body: "Usa área e perímetro para estimar quão redonda é a forma." },
    { title: "Solidez", body: "Área do objeto dividida pela área do casco convexo." },
    { title: "Convex hull", body: "Menor contorno convexo que contém todos os pontos do objeto." },
    { title: "Ruído importa", body: "Bordas serrilhadas aumentam perímetro e derrubam circularidade." },
  ],
  sections: [
    s("motivacao", "Motivação", "Quando área e caixa não bastam", "Dois objetos podem ter área parecida, mas formas completamente diferentes.", "shape-motivation", undefined, ["Área, perímetro e bounding box descrevem tamanho e localização, mas não capturam o desenho da forma. Um círculo, uma estrela e uma ferradura podem ocupar regiões parecidas e ainda assim significar coisas diferentes.", "Descritores como circularidade e solidez condensam diferenças visuais em números comparáveis. Eles ajudam a separar moedas de arruelas, gotas de riscos, células arredondadas de fragmentos irregulares.", "A ideia não é substituir o olhar humano, mas criar critérios explícitos para que um pipeline explique por que classificou um objeto de certo modo."], [{ type: "insight", title: "Descritor bom responde uma pergunta clara", body: "Circularidade pergunta sobre redondeza; solidez pergunta sobre preenchimento convexo." }]),
    s("circularidade", "Circularidade", "Área, perímetro e redondeza", "Circularidade compara a área real com o perímetro necessário para contorná-la.", "circularity-visual", "circularity-lab", ["A fórmula clássica é 4πA/P², onde A é área e P é perímetro. Um círculo ideal tende a 1. Formas alongadas, recortadas ou com contornos serrilhados produzem valores menores.", "O perímetro pesa ao quadrado, então pequenas irregularidades na borda podem reduzir bastante a circularidade. Por isso, pré-processamento e suavização de contorno podem mudar a leitura.", "Essa medida é útil quando o alvo esperado é aproximadamente redondo, como gotas, bolhas, grãos ou objetos circulares."], [{ type: "definition", title: "Circularidade", body: "Razão adimensional que mede quão próxima uma forma está de um círculo ideal." }, { type: "formula", title: "Fórmula", body: "A é área e P é perímetro.", formula: "circularidade = 4πA / P²" }, { type: "mistake", title: "Comparar sem controlar ruído", body: "Uma borda serrilhada aumenta o perímetro e pode fazer um círculo real parecer pouco circular." }]),
    s("convexidade", "Convexidade", "O que significa ser convexo", "Uma forma convexa não tem entradas profundas: qualquer segmento entre dois pontos internos permanece dentro dela.", "convexity-visual", undefined, ["Na prática visual, uma forma convexa parece sempre empurrada para fora. Se há reentrâncias, dentes ou vãos, ela deixa de ser convexa.", "OpenCV permite testar isso com isContourConvex, mas a interpretação mais útil vem comparando o contorno real com seu convex hull.", "Convexidade é uma propriedade global: um pequeno recorte pode mudar a classificação, mesmo se a maior parte do objeto parecer arredondada."], [{ type: "definition", title: "Forma convexa", body: "Forma em que o segmento entre quaisquer dois pontos internos não sai da região." }]),
    s("convex-hull", "Convex Hull", "A envoltória que abraça a forma", "O convex hull é o menor polígono convexo que contém todos os pontos do objeto.", "hull-visual", "hull-builder", ["Imagine esticar um elástico ao redor do objeto. Quando o elástico para de contrair, ele forma o casco convexo. As concavidades ficam por dentro, mas os extremos continuam tocando a borda.", "Em OpenCV, cv2.convexHull(cnt) retorna os pontos do casco. Em scikit-image, convex_hull_image cria uma máscara preenchida pela envoltória convexa.", "O hull é fundamental porque cria uma referência: quanto o objeto real perde em relação a uma versão sem reentrâncias?"], [{ type: "example", title: "Código OpenCV", body: "hull = cv2.convexHull(cnt); hull_area = cv2.contourArea(hull)" }, { type: "insight", title: "Elástico mental", body: "O hull ignora concavidades internas e preserva os pontos extremos." }]),
    s("solidez", "Solidez", "Quanto do casco está preenchido", "Solidez mede a razão entre área real e área do convex hull.", "solidity-visual", "solidity-comparison", ["A solidez é calculada como area / hull_area. Se a forma é convexa e bem preenchida, o valor fica próximo de 1. Se tem mordidas, braços separados por vãos ou concavidades profundas, o valor cai.", "Solidez não mede redondeza. Um retângulo perfeito pode ter solidez alta, mesmo não sendo circular. Por isso ela costuma ser combinada com circularidade, razão de aspecto e área.", "Quando hull_area é zero, o contorno é degenerado e a métrica deve ser descartada ou tratada com segurança."], [{ type: "definition", title: "Solidez", body: "Razão entre a área do objeto e a área de sua envoltória convexa." }, { type: "formula", title: "Fórmula", body: "Valores próximos de 1 indicam objeto convexo ou quase convexo.", formula: "solidez = area / area(convex hull)" }]),
    s("defeitos", "Defeitos Convexos", "Onde a forma entra para dentro", "Defeitos de convexidade localizam concavidades entre o contorno real e o hull.", "defects-visual", "defect-depth-demo", ["Defeitos convexos aparecem onde o casco passa por fora, mas o contorno real mergulha para dentro. Em uma mão aberta, os vãos entre dedos são exemplos clássicos.", "No OpenCV, convexityDefects usa índices do hull para estimar início, fim, ponto mais distante e profundidade de cada defeito.", "A profundidade do defeito ajuda a ignorar pequenas irregularidades e destacar concavidades realmente relevantes."], [{ type: "example", title: "Uso típico", body: "hull_idx = cv2.convexHull(cnt, returnPoints=False); defects = cv2.convexityDefects(cnt, hull_idx)" }, { type: "mistake", title: "Tratar todo defeito como semântico", body: "Ruído, oclusão e threshold ruim também criam concavidades aparentes." }]),
    s("combinacoes", "Combinação", "Descritores trabalham melhor juntos", "Circularidade e solidez respondem perguntas diferentes e se complementam.", "descriptor-grid", undefined, ["Um disco tende a ter circularidade alta e solidez alta. Uma estrela pode ter circularidade baixa e solidez baixa. Um retângulo pode ter solidez alta e circularidade moderada ou baixa.", "Essa combinação permite regras simples: se circularidade > limite e solidez > limite, classificar como objeto redondo e íntegro; se solidez baixa, sinalizar recorte ou concavidade.", "O segredo é calibrar limites com exemplos reais do conjunto de imagens, não escolher números apenas pela intuição."], [{ type: "insight", title: "Não existe descritor universal", body: "A mesma métrica pode ser ótima em um domínio e enganosa em outro." }]),
    s("pipeline", "Pipeline", "Do contorno à tabela", "Essas métricas viram colunas úteis em um DataFrame de objetos.", "pipeline-shape", undefined, ["Para cada contorno, calcule area, perimeter, circularity, hull, hull_area e solidity. Salve os resultados junto com label, bbox e centroide.", "Depois, visualize alguns casos extremos: maior circularidade, menor circularidade, menor solidez e maior área. Isso revela se a métrica está coerente ou se o pré-processamento precisa melhorar.", "Na entrega, mostre pelo menos uma imagem anotada com contorno real, hull e valores numéricos. Essa visualização torna a tabela interpretável."], [{ type: "example", title: "Colunas úteis", body: "label, area, perimeter, circularity, hull_area, solidity, bbox, centroid" }]),
    s("cuidados", "Cuidados", "Limites e armadilhas", "Descritores geométricos dependem da qualidade da segmentação.", "pitfalls-visual", undefined, ["Threshold ruim, buracos internos, objetos grudados e bordas serrilhadas mudam área, perímetro e hull. Antes de confiar nos números, inspecione máscaras e contornos.", "Circularidade é especialmente sensível ao perímetro. Solidez é sensível a concavidades e à fusão de objetos. Hull pode esconder recortes importantes se usado sozinho.", "Use filtros por área mínima, operações morfológicas e análise visual de amostras para evitar conclusões frágeis."], [{ type: "mistake", title: "Achar que solidez alta significa círculo", body: "Um quadrado e um retângulo podem ter solidez alta sem serem redondos." }]),
    s("quiz", "Revisão", "Quiz de revisão", "Teste os conceitos de circularidade, hull e solidez.", undefined, "quiz", ["Use o quiz para consolidar as diferenças entre descritores de forma."], []),
    s("glossario", "Glossário", "Termos essenciais", "Revise o vocabulário usado em análise de forma.", undefined, "glossary", ["Esses termos serão reutilizados na classificação baseada em regras."], []),
  ],
  summaryCards: [
    { title: "Circularidade mede redondeza", body: "Combina área e perímetro para comparar com um círculo ideal." },
    { title: "Hull é a envoltória convexa", body: "Abraça todos os pontos como um elástico tensionado." },
    { title: "Solidez mede preenchimento", body: "Compara área real com área do hull." },
    { title: "Convexidade não é circularidade", body: "Um retângulo pode ser convexo sem ser redondo." },
    { title: "Defeitos indicam concavidades", body: "Mostram onde o contorno real fica distante do hull." },
    { title: "Visualize extremos", body: "Sempre confira os maiores e menores valores da tabela." },
  ],
  quiz: [
    q("q1", "Qual fórmula representa circularidade?", "4πA/P²", "A/hull_area", "w/h", "a", "Circularidade usa área e perímetro para comparar com um círculo."),
    q("q2", "O que é convex hull?", "A menor envoltória convexa que contém os pontos do objeto.", "O centroide do contorno.", "O histograma da máscara.", "a", "O hull funciona como um elástico ao redor da forma."),
    q("q3", "Como calcular solidez?", "area / hull_area", "perimeter / area", "M10 / M00", "a", "Solidez compara área real com a área do casco convexo."),
    q("q4", "Um retângulo perfeito tende a ter qual propriedade?", "Solidez alta.", "Circularidade igual a 1.", "Hull area zero.", "a", "Retângulos são convexos, então sua área se aproxima da área do hull."),
    q("q5", "Por que circularidade cai com borda serrilhada?", "Porque o perímetro aumenta.", "Porque o centroide desaparece.", "Porque o hull fica sempre menor.", "a", "O perímetro entra ao quadrado na fórmula."),
    q("q6", "O que defeitos convexos indicam?", "Concavidades entre contorno real e hull.", "Pixels de fundo desconectados.", "Somente objetos circulares.", "a", "Defeitos mostram mergulhos do contorno para dentro do casco."),
    q("q7", "Qual cuidado é necessário ao usar hull_area?", "Verificar se não é zero antes de dividir.", "Converter para RGB sempre.", "Usar apenas conectividade-4.", "a", "Contornos degenerados podem gerar área inválida."),
    q("q8", "Por que combinar circularidade e solidez?", "Porque elas medem aspectos diferentes da forma.", "Porque uma anula a outra.", "Porque ambas são sempre iguais.", "a", "Redondeza e preenchimento convexo são propriedades complementares."),
  ],
  glossary: [
    g("Circularidade", "Medida de quão próxima uma forma está de um círculo ideal."),
    g("Perímetro", "Comprimento do contorno do objeto."),
    g("Área", "Quantidade de pixels ou área geométrica ocupada pelo objeto."),
    g("Convexidade", "Propriedade de uma forma sem reentrâncias que quebrem segmentos internos."),
    g("Convex hull", "Menor polígono convexo que contém todos os pontos do objeto."),
    g("Solidez", "Razão entre a área do objeto e a área do convex hull."),
    g("Defeito convexo", "Concavidade medida entre o contorno real e o casco convexo."),
    g("Contorno", "Sequência de pontos que descreve a borda do objeto."),
    g("Borda serrilhada", "Contorno irregular causado por discretização, ruído ou segmentação ruim."),
    g("Descritor de forma", "Número ou conjunto de números que resume uma propriedade geométrica."),
    g("Objeto convexo", "Objeto cujo hull coincide aproximadamente com o próprio contorno."),
    g("Regra de classificação", "Critério explícito baseado em limites de descritores."),
  ],
};

function s(id: string, eyebrow: string, title: string, lead: string, visual: string | undefined, interactive: string | undefined, paragraphs: string[], blocks: LessonContent["sections"][number]["blocks"]) { return { id, eyebrow, title, lead, visual, interactive, paragraphs, blocks }; }
function q(id: string, prompt: string, a: string, b: string, c: string, correctOptionId: string, feedback: string) { return { id, prompt, options: [{ id: "a", label: a }, { id: "b", label: b }, { id: "c", label: c }], correctOptionId, feedback }; }
function g(term: string, definition: string) { return { term, definition }; }
