import type { LessonContent } from "../../../types/content";

export const segmentacaoPorInstanciasContent: LessonContent = {
  id: "segmentacao-por-instancias",
  title: "Segmentação por Instâncias",
  subtitle: "Como separar objetos individuais da mesma classe usando caixas, scores e uma máscara para cada instância.",
  description: "Aula interativa sobre segmentação por instâncias, Mask R-CNN, propostas, NMS, scores, máscaras por objeto, COCO e diferenças para segmentação semântica e panóptica.",
  primaryCategoryId: "inteligencia-artificial",
  secondaryCategoryId: "computacao",
  level: "Avançado",
  estimatedTime: "50-60 min",
  tags: ["Visão Computacional", "Segmentação por Instâncias", "Mask R-CNN", "Detecção", "COCO", "Deep Learning"],
  learningObjectives: ["Diferenciar segmentação semântica e por instâncias.", "Entender a saída com boxes, labels, scores e masks.", "Interpretar o papel de propostas, NMS e limiares de confiança.", "Compreender a ideia central do Mask R-CNN.", "Avaliar máscaras por instância com sobreposição e erros de duplicação.", "Reconhecer limites como objetos ocluídos, grudados e classes fora do treino."],
  prerequisites: ["Segmentação semântica.", "Bounding boxes e IoU.", "Noções de redes convolucionais."],
  references: [
    { title: "Mask R-CNN", source: "He, Gkioxari, Dollár e Girshick — arXiv/ICCV", url: "https://arxiv.org/abs/1703.06870", note: "Propõe framework para detectar objetos e gerar uma máscara para cada instância." },
    { title: "TorchVision — maskrcnn_resnet50_fpn", source: "PyTorch docs", url: "https://pytorch.org/vision/stable/models/generated/torchvision.models.detection.maskrcnn_resnet50_fpn.html", note: "Documenta entradas, alvos de treino e saídas de inferência do Mask R-CNN." },
    { title: "COCO Dataset", source: "COCO", url: "https://cocodataset.org/#home", note: "Dataset e benchmark com tarefas de detecção, segmentação por instâncias, keypoints e panóptica." },
    { title: "Faster R-CNN: Towards Real-Time Object Detection with Region Proposal Networks", source: "Ren et al. — arXiv", url: "https://arxiv.org/abs/1506.01497", note: "Base conceitual de propostas de região e detecção em dois estágios." },
    { title: "Microsoft COCO: Common Objects in Context", source: "Lin et al. — arXiv", url: "https://arxiv.org/abs/1405.0312", note: "Descreve o dataset COCO e seu foco em objetos em contexto." },
  ],
  heroVisual: "instances-hero",
  openingText: "Segmentação semântica pinta todos os carros como 'carro'. Segmentação por instâncias vai além: separa carro 1, carro 2, carro 3, mesmo que todos pertençam à mesma classe. A saída é uma lista de objetos, e cada objeto vem com caixa, classe, confiança e máscara própria. Essa diferença muda tudo quando precisamos contar, rastrear, medir ou manipular objetos individualmente.",
  quickFacts: [
    { title: "Uma máscara por objeto", body: "Cada instância tem sua própria região segmentada." },
    { title: "Lista, não mapa único", body: "A saída é um conjunto de detecções com boxes, labels, scores e masks." },
    { title: "Scores filtram ruído", body: "Limiar de confiança decide quais instâncias aparecem." },
    { title: "NMS remove duplicatas", body: "Detecções sobrepostas demais competem entre si." },
  ],
  sections: [
    s("ideia", "Ideia Central", "Separar indivíduos", "A tarefa identifica cada objeto individual e sua máscara própria.", "instances-idea", "instance-picker", ["Se dois objetos da mesma classe aparecem juntos, a semântica os funde em uma única classe. A segmentação por instâncias precisa separá-los como entidades distintas.", "Isso é essencial para contagem, rastreamento, inspeção, robótica e análise de cenas com objetos repetidos.", "A saída deixa de ser apenas uma imagem de classes e passa a ser uma lista de instâncias detectadas."], [{ type: "definition", title: "Instância", body: "Ocorrência individual de um objeto dentro de uma classe." }]),
    s("comparacao", "Comparação", "Semântica, instâncias e panóptica", "As três tarefas organizam pixels e objetos de formas diferentes.", "instance-comparison", undefined, ["Segmentação semântica responde a classe de cada pixel. Segmentação por instâncias separa objetos contáveis, normalmente coisas como pessoa, carro e animal. Segmentação panóptica combina classes de coisas e regiões de fundo, tentando descrever a cena inteira.", "A instância não substitui sempre a semântica: ela é especialmente forte quando indivíduos importam.", "Se o problema é medir área total de vegetação, semântica pode bastar. Se é contar frutas, instâncias são necessárias."], [{ type: "insight", title: "Coisas vs fundo", body: "Instâncias focam objetos contáveis; panóptica também organiza regiões amorfas como céu e estrada." }]),
    s("saida", "Saída", "Boxes, labels, scores e masks", "Modelos de instância retornam uma lista de detecções.", "instance-output", "output-filter", ["Em TorchVision, a inferência do Mask R-CNN retorna campos como boxes, labels, scores e masks. Cada posição da lista corresponde a uma instância.", "A máscara pode ser suave, com valores entre 0 e 1, e costuma ser binarizada por um limiar. O score controla a confiança da detecção inteira.", "Essa estrutura é diferente da semântica: não há apenas um mapa final, mas múltiplas máscaras que podem até se sobrepor antes do pós-processamento."], [{ type: "example", title: "Saída típica", body: "[{box, label, score, mask}, {box, label, score, mask}, ...]" }]),
    s("mask-rcnn", "Mask R-CNN", "Detecção mais ramo de máscara", "Mask R-CNN estende Faster R-CNN adicionando uma cabeça para prever máscaras.", "maskrcnn-visual", "mask-head-demo", ["A ideia central é detectar regiões candidatas, classificar cada uma, ajustar sua caixa e prever uma máscara para aquela região. A cabeça de máscara roda em paralelo com as cabeças de classe e caixa.", "Esse desenho é flexível: a rede aproveita uma estrutura de detecção e adiciona segmentação fina por objeto.", "Na prática, a qualidade da caixa afeta a máscara: se a região proposta é ruim, a máscara começa com uma hipótese ruim."], [{ type: "definition", title: "Cabeça de máscara", body: "Parte do modelo que prevê a máscara binária de uma instância candidata." }]),
    s("propostas", "Propostas", "Antes da máscara vem a hipótese", "Modelos de dois estágios primeiro sugerem regiões onde pode haver objetos.", "proposal-visual", undefined, ["Um detector de dois estágios trabalha com propostas de região. Primeiro ele pergunta onde talvez exista um objeto; depois refina classe, caixa e máscara.", "Esse processo ajuda a concentrar computação em regiões relevantes, mas introduz dependência: instâncias que não recebem boas propostas podem ser perdidas.", "Objetos pequenos, parcialmente ocluídos ou muito próximos são casos difíceis."], [{ type: "mistake", title: "Achar que máscara corrige tudo", body: "Se a proposta ou caixa falha, a cabeça de máscara pode não recuperar o objeto." }]),
    s("nms", "Pós-Processamento", "NMS e limiar de score", "Múltiplas detecções podem disputar o mesmo objeto.", "nms-visual", "nms-simulator", ["O modelo pode gerar várias hipóteses para o mesmo objeto. Non-Maximum Suppression reduz duplicatas mantendo a detecção mais confiante entre caixas muito sobrepostas.", "Além disso, um limiar de score remove detecções fracas. Se o corte é alto demais, objetos reais somem; se é baixo demais, surgem falsos positivos.", "Ajustar score e NMS é parte do pipeline, não detalhe cosmético."], [{ type: "definition", title: "NMS", body: "Técnica que remove detecções redundantes com alta sobreposição." }]),
    s("avaliacao", "Avaliação", "Acertos, duplicatas e perdas", "Avaliar instâncias exige verificar classe, máscara e correspondência entre objetos.", "instance-eval", undefined, ["Um bom resultado precisa detectar o objeto correto, atribuir a classe certa e produzir uma máscara bem sobreposta. Erros comuns incluem duplicar uma instância, juntar duas em uma ou perder objeto pequeno.", "Métricas de benchmarks costumam avaliar sobreposição em múltiplos limiares, mas a inspeção visual continua indispensável.", "Para projetos práticos, conte falsos positivos, falsos negativos e erros de separação."], [{ type: "insight", title: "Erro de contagem é erro central", body: "Na segmentação por instâncias, uma máscara bonita ainda pode falhar se junta dois objetos." }]),
    s("dados", "Dados", "Anotar instâncias é caro", "Cada objeto precisa de máscara e identidade própria.", "instance-data", undefined, ["A anotação de instâncias exige desenhar uma região para cada objeto separado. Isso é mais trabalhoso que uma máscara semântica quando há muitos objetos da mesma classe.", "Datasets como COCO tornaram a tarefa comparável, mas projetos reais ainda precisam lidar com classes específicas, domínio visual e critérios de anotação.", "Consistência importa: dois anotadores devem concordar sobre quando objetos grudados são uma ou duas instâncias."], [{ type: "mistake", title: "Não definir regra de separação", body: "Sem critério de anotação, o modelo aprende decisões inconsistentes." }]),
    s("limites", "Limitações", "Oclusão, sobreposição e domínio", "Separar indivíduos é difícil quando evidências visuais se misturam.", "instance-limits", undefined, ["Objetos ocluídos, transparentes, muito pequenos ou grudados podem confundir o modelo. Mudanças de câmera, iluminação e contexto também afetam generalização.", "Em cenas densas, a saída pode exigir calibração cuidadosa de score e NMS para não perder objetos reais nem criar duplicatas.", "Quando a cena inteira precisa ser explicada, a segmentação panóptica pode ser um próximo passo."], [{ type: "insight", title: "Instância não é mágica", body: "Ela adiciona identidade aos objetos, mas depende de dados, propostas e pós-processamento." }]),
    s("quiz", "Revisão", "Quiz de revisão", "Teste instâncias, Mask R-CNN, scores e NMS.", undefined, "quiz", ["Revise antes de comparar pipelines clássicos e deep learning."], []),
    s("glossario", "Glossário", "Termos essenciais", "Fixe o vocabulário de segmentação por instâncias.", undefined, "glossary", ["Esses termos aparecem em APIs, papers e benchmarks."], []),
  ],
  summaryCards: [
    { title: "Instância separa indivíduos", body: "Objetos da mesma classe recebem máscaras distintas." },
    { title: "Saída é uma lista", body: "Cada detecção tem box, label, score e mask." },
    { title: "Mask R-CNN adiciona máscara", body: "Extende detecção com uma cabeça de segmentação." },
    { title: "Score filtra confiança", body: "Limiar baixo aceita ruído; alto pode perder objetos." },
    { title: "NMS reduz duplicatas", body: "Detecções sobrepostas competem entre si." },
    { title: "Anotação custa caro", body: "Cada objeto precisa de máscara individual." },
  ],
  quiz: [
    q("q1", "O que segmentação por instâncias separa?", "Objetos individuais da mesma classe.", "Apenas fundo e primeiro plano.", "Somente histogramas.", "a", "Ela distingue indivíduos como carro 1 e carro 2."),
    q("q2", "Qual campo indica confiança da detecção?", "score", "mask", "width", "a", "Score resume a confiança da instância detectada."),
    q("q3", "O que Mask R-CNN adiciona ao Faster R-CNN?", "Uma cabeça de máscara.", "Um filtro de Otsu.", "Uma transformada de Hough obrigatória.", "a", "A arquitetura prevê máscaras em paralelo a classe e caixa."),
    q("q4", "Para que serve NMS?", "Remover detecções duplicadas muito sobrepostas.", "Aumentar brilho da imagem.", "Transformar máscaras em logits.", "a", "NMS mantém hipóteses mais confiantes entre sobreposições."),
    q("q5", "Qual saída é típica em TorchVision Mask R-CNN?", "boxes, labels, scores e masks.", "apenas uma classe global.", "somente uma máscara semântica única.", "a", "A inferência retorna uma lista de dicionários por imagem."),
    q("q6", "O que acontece se o score threshold for alto demais?", "Objetos reais podem desaparecer.", "Todos os falsos positivos aumentam sempre.", "As máscaras ficam RGB automaticamente.", "a", "Cortes altos rejeitam hipóteses fracas, inclusive algumas verdadeiras."),
    q("q7", "Qual erro é central em instâncias?", "Juntar dois objetos em uma máscara.", "Ter muitas classes de fundo.", "Usar imagens coloridas.", "a", "Separar indivíduos é parte essencial da tarefa."),
    q("q8", "Por que anotação é mais trabalhosa?", "Cada objeto precisa de máscara própria.", "Não há classes.", "Não usa imagens reais.", "a", "A identidade individual aumenta custo e complexidade."),
  ],
  glossary: [
    g("Instância", "Objeto individual dentro de uma classe."),
    g("Segmentação por instâncias", "Tarefa de detectar objetos e gerar máscara para cada indivíduo."),
    g("Box", "Retângulo que localiza uma instância."),
    g("Score", "Confiança associada a uma detecção."),
    g("Mask", "Região segmentada de uma instância."),
    g("Mask R-CNN", "Modelo que combina detecção e previsão de máscara por objeto."),
    g("Proposta de região", "Hipótese de área onde pode haver um objeto."),
    g("NMS", "Supressão de detecções redundantes por sobreposição."),
    g("COCO", "Dataset e benchmark usado em detecção e segmentação."),
    g("Oclusão", "Situação em que um objeto cobre parte de outro."),
    g("Panóptica", "Segmentação que combina instâncias de objetos e regiões semânticas de fundo."),
    g("Falso positivo", "Instância detectada que não deveria existir."),
  ],
};

function s(id: string, eyebrow: string, title: string, lead: string, visual: string | undefined, interactive: string | undefined, paragraphs: string[], blocks: LessonContent["sections"][number]["blocks"]) { return { id, eyebrow, title, lead, visual, interactive, paragraphs, blocks }; }
function q(id: string, prompt: string, a: string, b: string, c: string, correctOptionId: string, feedback: string) { return { id, prompt, options: [{ id: "a", label: a }, { id: "b", label: b }, { id: "c", label: c }], correctOptionId, feedback }; }
function g(term: string, definition: string) { return { term, definition }; }
